/**
 * Installable offline app (feature pwa) – the pure part, shared by the web app manifest
 * (src/app/manifest.ts), the service-worker registration (src/components/site/PwaRegister.tsx)
 * and the tests. The service worker itself is generated by scripts/postexport.mjs from
 * scripts/pwa/sw.template.js (see scripts/pwa/build.mjs).
 */

/** Browser UI colour of the installed app and of the address bar: the page background. */
export const PWA_THEME_COLOR = "#0b0b0d";
/** Splash-screen background while the installed app starts. */
export const PWA_BACKGROUND_COLOR = "#0b0b0d";

/** PNG icons rendered from public/icon.svg by scripts/generate-icons.mjs (committed to public/icons/). */
export const PWA_ICON_FILES = {
  icon192: "/icons/icon-192.png",
  icon512: "/icons/icon-512.png",
  maskable512: "/icons/icon-maskable-512.png",
  appleTouch: "/icons/apple-touch-icon.png",
} as const;

/** Where the service worker lives and what it controls: `/sw.js` and `/` under the base path. */
export function serviceWorkerUrl(basePath: string): string {
  return `${basePath.replace(/\/+$/, "")}/sw.js`;
}

export function serviceWorkerScope(basePath: string): string {
  return `${basePath.replace(/\/+$/, "")}/`;
}

const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1", "[::1]", "::1"]);

/**
 * The service worker is registered only in production builds (a dev server's hot reloading must never be
 * served from a cache) and only over HTTPS or on localhost – the origins browsers allow service workers on.
 */
export function canRegisterServiceWorker(env: { production: boolean; protocol: string; hostname: string; supported: boolean }): boolean {
  if (!env.production || !env.supported) return false;
  if (env.protocol === "https:") return true;
  return env.protocol === "http:" && (LOCAL_HOSTS.has(env.hostname) || env.hostname.endsWith(".localhost"));
}

export interface ManifestIcon {
  src: string;
  sizes: string;
  type: string;
  purpose?: "any" | "maskable" | "monochrome";
}

export interface WebAppManifest {
  id: string;
  name: string;
  short_name: string;
  description: string;
  lang: string;
  dir: "ltr";
  start_url: string;
  scope: string;
  display: "standalone";
  display_override: ("standalone" | "minimal-ui")[];
  orientation: "any";
  theme_color: string;
  background_color: string;
  categories: string[];
  icons: ManifestIcon[];
  shortcuts: { name: string; short_name: string; url: string; icons: ManifestIcon[] }[];
}

/**
 * The web app manifest (out/manifest.webmanifest). One manifest serves every language, so it starts the
 * installed app on the default locale's landing page; every URL carries the base path because the site
 * may live in a sub-folder (GitHub Pages project site).
 */
export function buildWebAppManifest(opts: {
  basePath: string;
  name: string;
  /** Label under the home-screen icon; the name when omitted. */
  shortName?: string;
  description: string;
  locale: string;
  simulatorLabel: string;
}): WebAppManifest {
  const base = opts.basePath.replace(/\/+$/, "");
  const icon = (path: string) => `${base}${path}`;
  return {
    id: `${base}/`,
    name: opts.name,
    short_name: opts.shortName ?? opts.name,
    description: opts.description,
    lang: opts.locale,
    dir: "ltr",
    start_url: `${base}/${opts.locale}/`,
    scope: `${base}/`,
    display: "standalone",
    display_override: ["standalone", "minimal-ui"],
    orientation: "any",
    theme_color: PWA_THEME_COLOR,
    background_color: PWA_BACKGROUND_COLOR,
    categories: ["entertainment", "games", "music"],
    icons: [
      { src: icon("/icon.svg"), sizes: "any", type: "image/svg+xml", purpose: "any" },
      { src: icon(PWA_ICON_FILES.icon192), sizes: "192x192", type: "image/png", purpose: "any" },
      { src: icon(PWA_ICON_FILES.icon512), sizes: "512x512", type: "image/png", purpose: "any" },
      { src: icon(PWA_ICON_FILES.maskable512), sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
    shortcuts: [
      {
        name: opts.simulatorLabel,
        short_name: opts.simulatorLabel,
        url: `${base}/${opts.locale}/simulator/`,
        icons: [{ src: icon(PWA_ICON_FILES.icon192), sizes: "192x192", type: "image/png" }],
      },
    ],
  };
}

/** Chrome's install prompt event (not in lib.dom yet). */
export interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>;
  readonly userChoice: Promise<{ outcome: "accepted" | "dismissed"; platform?: string }>;
}
