/**
 * --- fl-overhaul --- GENERATED by `node scripts/fl-balance.mjs --apply` (Stage 2's balance tuner) – do not edit by hand.
 *
 * FL_STRENGTH: every tuned fighter's win share on the balance test's seeds (both arenas, a draw half, in %) and its
 * Bradley–Terry strength from the same duels, normalised to a geometric mean of 1 within its division (2 = twice the odds
 * of an average division mate). FL_RATINGS_HASH is flRosterHash() of the roster the numbers were measured on; the tests
 * warn (without failing) when the roster has changed since – re-run the tuner then.
 */

export interface FlRating {
  /** Win share on the balance test's seeds, in %. */
  win: number;
  /** Bradley–Terry strength, geometric mean 1 per division. */
  strength: number;
}

export const FL_RATINGS_HASH = "eab19272";

/** The division fingerprints (flDivisionHash) the ratings were measured on. */
export const FL_RATINGS_DIVISION_HASHES: Readonly<Record<string, string>> = {
  marvel: "026b6016",
  dc: "b361409d",
  nintendo: "3285bafa",
  league: "f4f48ec2",
  fighting: "e74feef5",
  legends: "831d72c7",
  shonen: "69716220",
  starWars: "175b0683",
  fantasy: "863f6781",
  monsters: "3a64e6ce",
  action: "63ca7c2c",
  tv: "55060f16",
  pokemon: "02b17646",
  modernAnime: "c8a90376",
  sandbox: "42aaad10",
  horror: "ce437ac8",
  animated: "f9d5382b",
  cartoons: "37d928b6",
  wildcard: "16ffb21d",
};

export const FL_STRENGTH: Readonly<Record<string, FlRating>> = {
  // marvel
  thor: { win: 50, strength: 1 },
  loki: { win: 51.9, strength: 1.064 },
  spiderman: { win: 38.4, strength: 0.675 },
  ironman: { win: 57.9, strength: 1.305 },
  captainamerica: { win: 61.1, strength: 1.459 },
  hulk: { win: 47.2, strength: 0.911 },
  venom: { win: 48.2, strength: 0.94 },
  thanos: { win: 51.9, strength: 1.064 },
  deadpool: { win: 50, strength: 1 },
  wolverine: { win: 43.5, strength: 0.804 },
  // dc
  superman: { win: 56, strength: 1.215 },
  batman: { win: 45.3, strength: 0.856 },
  joker: { win: 47, strength: 0.907 },
  wonderwoman: { win: 42.9, strength: 0.791 },
  flash: { win: 59.6, strength: 1.367 },
  aquaman: { win: 56, strength: 1.215 },
  harleyquinn: { win: 45.9, strength: 0.873 },
  darkseid: { win: 47.6, strength: 0.925 },
  // nintendo
  mario: { win: 49.1, strength: 0.969 },
  link: { win: 48.2, strength: 0.939 },
  samus: { win: 46.8, strength: 0.896 },
  captainfalcon: { win: 52.8, strength: 1.097 },
  littlemac: { win: 41.7, strength: 0.754 },
  sonic: { win: 48.2, strength: 0.939 },
  kirby: { win: 61.1, strength: 1.458 },
  donkeykong: { win: 59.3, strength: 1.367 },
  bowser: { win: 50.4, strength: 1.015 },
  shadow: { win: 42.6, strength: 0.779 },
  // league
  yuumi: { win: 45.3, strength: 0.855 },
  katarina: { win: 47.7, strength: 0.925 },
  garen: { win: 54.8, strength: 1.169 },
  jinx: { win: 43.5, strength: 0.806 },
  ahri: { win: 39.3, strength: 0.701 },
  lux: { win: 62.5, strength: 1.514 },
  yasuo: { win: 51.2, strength: 1.04 },
  leesin: { win: 56, strength: 1.216 },
  // fighting
  ryu: { win: 43.2, strength: 0.797 },
  ken: { win: 60.5, strength: 1.42 },
  chunli: { win: 44.8, strength: 0.84 },
  scorpion: { win: 42.7, strength: 0.783 },
  subzero: { win: 47.9, strength: 0.933 },
  akuma: { win: 58.9, strength: 1.346 },
  liukang: { win: 56.8, strength: 1.254 },
  raiden: { win: 39.1, strength: 0.692 },
  kazuya: { win: 56.3, strength: 1.233 },
  // legends
  masterchief: { win: 57.8, strength: 1.299 },
  doomslayer: { win: 53.2, strength: 1.11 },
  kratos: { win: 50, strength: 1.001 },
  zeus: { win: 36, strength: 0.622 },
  laracroft: { win: 51.6, strength: 1.054 },
  cloud: { win: 50, strength: 1.001 },
  sephiroth: { win: 50.5, strength: 1.018 },
  arthurmorgan: { win: 56.3, strength: 1.232 },
  pacman: { win: 44.8, strength: 0.842 },
  // shonen
  goku: { win: 49.5, strength: 0.981 },
  vegeta: { win: 42.7, strength: 0.781 },
  naruto: { win: 49.5, strength: 0.981 },
  sasuke: { win: 42.7, strength: 0.781 },
  luffy: { win: 58.3, strength: 1.321 },
  saitama: { win: 41.7, strength: 0.754 },
  zoro: { win: 50, strength: 0.998 },
  itachi: { win: 46.9, strength: 0.899 },
  frieza: { win: 68.8, strength: 1.908 },
  // starWars
  luke: { win: 57.2, strength: 1.263 },
  vader: { win: 47, strength: 0.908 },
  yoda: { win: 53.6, strength: 1.123 },
  maul: { win: 50.6, strength: 1.02 },
  obiwan: { win: 43.5, strength: 0.808 },
  kyloren: { win: 42.9, strength: 0.792 },
  palpatine: { win: 56, strength: 1.214 },
  mandalorian: { win: 49.5, strength: 0.981 },
  // fantasy
  harrypotter: { win: 53.7, strength: 1.128 },
  voldemort: { win: 42.8, strength: 0.785 },
  gandalf: { win: 42.2, strength: 0.771 },
  legolas: { win: 54.7, strength: 1.168 },
  hermione: { win: 48, strength: 0.933 },
  dumbledore: { win: 54.2, strength: 1.148 },
  aragorn: { win: 45.4, strength: 0.856 },
  sauron: { win: 51, strength: 1.035 },
  geralt: { win: 58.3, strength: 1.32 },
  // monsters
  godzilla: { win: 64.2, strength: 1.567 },
  kingkong: { win: 40.8, strength: 0.749 },
  alien: { win: 55.9, strength: 1.2 },
  predator: { win: 46.7, strength: 0.9 },
  trex: { win: 43.3, strength: 0.811 },
  jaws: { win: 49.2, strength: 0.973 },
  // action
  johnwick: { win: 56, strength: 1.216 },
  neo: { win: 35.7, strength: 0.622 },
  terminator: { win: 48.3, strength: 0.944 },
  robocop: { win: 49.4, strength: 0.982 },
  indianajones: { win: 47.6, strength: 0.926 },
  jamesbond: { win: 54.2, strength: 1.147 },
  rambo: { win: 56.6, strength: 1.24 },
  jacksparrow: { win: 52.4, strength: 1.082 },
  // tv
  homelander: { win: 49.5, strength: 0.983 },
  omniman: { win: 51, strength: 1.035 },
  aang: { win: 45.9, strength: 0.872 },
  zuko: { win: 51, strength: 1.035 },
  jonsnow: { win: 54.2, strength: 1.147 },
  nightking: { win: 47.4, strength: 0.918 },
  walterwhite: { win: 55.3, strength: 1.187 },
  eleven: { win: 49, strength: 0.966 },
  daenerys: { win: 46.9, strength: 0.902 },
  // pokemon
  pikachu: { win: 54.2, strength: 1.143 },
  charizard: { win: 52.8, strength: 1.093 },
  mewtwo: { win: 41, strength: 0.749 },
  lucario: { win: 51.4, strength: 1.046 },
  greninja: { win: 42.4, strength: 0.783 },
  gengar: { win: 51.4, strength: 1.046 },
  snorlax: { win: 57, strength: 1.249 },
  // modernAnime
  gojo: { win: 51.8, strength: 1.06 },
  sukuna: { win: 51.2, strength: 1.04 },
  tanjiro: { win: 46.4, strength: 0.891 },
  nezuko: { win: 52.4, strength: 1.081 },
  levi: { win: 40.4, strength: 0.732 },
  eren: { win: 49.4, strength: 0.981 },
  deku: { win: 52.4, strength: 1.081 },
  bakugo: { win: 56, strength: 1.214 },
  // sandbox
  steve: { win: 59.7, strength: 1.383 },
  creeper: { win: 57, strength: 1.261 },
  enderman: { win: 50, strength: 1.005 },
  jonesy: { win: 54.2, strength: 1.152 },
  peely: { win: 26.4, strength: 0.447 },
  noob: { win: 55.6, strength: 1.205 },
  crewmate: { win: 47.2, strength: 0.918 },
  // horror
  freddy: { win: 52.8, strength: 1.092 },
  jason: { win: 45.8, strength: 0.876 },
  michaelmyers: { win: 57, strength: 1.248 },
  ghostface: { win: 50, strength: 1 },
  pennywise: { win: 44.5, strength: 0.838 },
  chucky: { win: 48.6, strength: 0.957 },
  leatherface: { win: 51.4, strength: 1.045 },
  // animated
  buzz: { win: 49.3, strength: 0.977 },
  woody: { win: 47.2, strength: 0.915 },
  shrek: { win: 45.9, strength: 0.875 },
  pussinboots: { win: 47.2, strength: 0.915 },
  toothless: { win: 62.5, strength: 1.496 },
  elsa: { win: 50.7, strength: 1.022 },
  mrincredible: { win: 47.3, strength: 0.915 },
  // cartoons
  homer: { win: 59.7, strength: 1.376 },
  spongebob: { win: 35.4, strength: 0.615 },
  rick: { win: 50, strength: 0.999 },
  bugsbunny: { win: 68.1, strength: 1.833 },
  tom: { win: 45.2, strength: 0.852 },
  jerry: { win: 54.2, strength: 1.145 },
  popeye: { win: 37.5, strength: 0.661 },
};
