/**
 * --- fl-overhaul --- GENERATED by `node scripts/fl-balance.mjs --apply` (Stage 2's balance tuner) – do not edit by hand.
 *
 * FL_STRENGTH: every tuned fighter's win share on the balance test's seeds (both arenas, a draw half, in %) and its
 * Bradley–Terry strength from the same duels, normalised to a geometric mean of 1 within its division (2 = twice the odds
 * of an average division mate). FL_RATINGS_HASH is flRosterHash() of the roster the numbers were measured on; the tests
 * warn (without failing) when the roster has changed since – re-run the tuner then.
 */

export interface FlRating {
  /** Win share on the balance test's seeds, in %. */
  win: number;
  /** Bradley–Terry strength, geometric mean 1 per division. */
  strength: number;
}

export const FL_RATINGS_HASH = "66c7ff94";

/** The division fingerprints (flDivisionHash) the ratings were measured on. */
export const FL_RATINGS_DIVISION_HASHES: Readonly<Record<string, string>> = {
  marvel: "a9bce66a",
  dc: "daf02206",
  nintendo: "3285bafa",
  league: "f3604b6e",
  fighting: "f0971ee8",
  legends: "831d72c7",
  shonen: "53c32f3e",
  starWars: "d6ebf706",
  fantasy: "863f6781",
  monsters: "3a64e6ce",
  action: "f1021acb",
  tv: "8f18a0d6",
  pokemon: "02b17646",
  modernAnime: "57d5b036",
  sandbox: "1a79e81b",
  horror: "ce437ac8",
  animated: "f9d5382b",
  cartoons: "59b141ce",
  wildcard: "16ffb21d",
};

export const FL_STRENGTH: Readonly<Record<string, FlRating>> = {
  // marvel
  thor: { win: 50, strength: 1 },
  loki: { win: 57, strength: 1.262 },
  spiderman: { win: 48.2, strength: 0.94 },
  ironman: { win: 57, strength: 1.262 },
  captainamerica: { win: 46.3, strength: 0.883 },
  hulk: { win: 50.9, strength: 1.031 },
  venom: { win: 48.2, strength: 0.94 },
  thanos: { win: 48.2, strength: 0.94 },
  deadpool: { win: 52.8, strength: 1.097 },
  wolverine: { win: 41.7, strength: 0.756 },
  // dc
  superman: { win: 58.4, strength: 1.315 },
  batman: { win: 51.1, strength: 1.039 },
  joker: { win: 52.4, strength: 1.081 },
  wonderwoman: { win: 41.7, strength: 0.76 },
  flash: { win: 61.9, strength: 1.483 },
  aquaman: { win: 44.7, strength: 0.839 },
  harleyquinn: { win: 44.7, strength: 0.839 },
  darkseid: { win: 45.2, strength: 0.855 },
  // nintendo
  mario: { win: 49.1, strength: 0.969 },
  link: { win: 48.2, strength: 0.939 },
  samus: { win: 46.8, strength: 0.896 },
  captainfalcon: { win: 52.8, strength: 1.097 },
  littlemac: { win: 41.7, strength: 0.754 },
  sonic: { win: 48.2, strength: 0.939 },
  kirby: { win: 61.1, strength: 1.458 },
  donkeykong: { win: 59.3, strength: 1.367 },
  bowser: { win: 50.4, strength: 1.015 },
  shadow: { win: 42.6, strength: 0.779 },
  // league
  yuumi: { win: 43.5, strength: 0.804 },
  katarina: { win: 63.1, strength: 1.549 },
  garen: { win: 64.3, strength: 1.614 },
  jinx: { win: 38.1, strength: 0.671 },
  ahri: { win: 45.8, strength: 0.87 },
  lux: { win: 52.4, strength: 1.08 },
  yasuo: { win: 46.5, strength: 0.888 },
  leesin: { win: 46.5, strength: 0.888 },
  // fighting
  ryu: { win: 51.6, strength: 1.053 },
  ken: { win: 53.7, strength: 1.128 },
  chunli: { win: 48, strength: 0.933 },
  scorpion: { win: 41.7, strength: 0.757 },
  subzero: { win: 44.3, strength: 0.826 },
  akuma: { win: 57.3, strength: 1.275 },
  liukang: { win: 42.7, strength: 0.784 },
  raiden: { win: 60.9, strength: 1.443 },
  kazuya: { win: 50, strength: 1 },
  // legends
  masterchief: { win: 57.8, strength: 1.299 },
  doomslayer: { win: 53.2, strength: 1.11 },
  kratos: { win: 50, strength: 1.001 },
  zeus: { win: 36, strength: 0.622 },
  laracroft: { win: 51.6, strength: 1.054 },
  cloud: { win: 50, strength: 1.001 },
  sephiroth: { win: 50.5, strength: 1.018 },
  arthurmorgan: { win: 56.3, strength: 1.232 },
  pacman: { win: 44.8, strength: 0.842 },
  // shonen
  goku: { win: 53.7, strength: 1.127 },
  vegeta: { win: 44.8, strength: 0.838 },
  naruto: { win: 47.4, strength: 0.914 },
  sasuke: { win: 42.8, strength: 0.781 },
  luffy: { win: 49, strength: 0.963 },
  saitama: { win: 41.7, strength: 0.754 },
  zoro: { win: 49, strength: 0.963 },
  itachi: { win: 52.1, strength: 1.069 },
  frieza: { win: 69.8, strength: 1.982 },
  // starWars
  luke: { win: 56.6, strength: 1.24 },
  vader: { win: 56, strength: 1.216 },
  yoda: { win: 51.2, strength: 1.04 },
  maul: { win: 54.2, strength: 1.147 },
  obiwan: { win: 57.2, strength: 1.265 },
  kyloren: { win: 39.3, strength: 0.702 },
  palpatine: { win: 41.7, strength: 0.76 },
  mandalorian: { win: 44.1, strength: 0.823 },
  // fantasy
  harrypotter: { win: 53.7, strength: 1.128 },
  voldemort: { win: 42.8, strength: 0.785 },
  gandalf: { win: 42.2, strength: 0.771 },
  legolas: { win: 54.7, strength: 1.168 },
  hermione: { win: 48, strength: 0.933 },
  dumbledore: { win: 54.2, strength: 1.148 },
  aragorn: { win: 45.4, strength: 0.856 },
  sauron: { win: 51, strength: 1.035 },
  geralt: { win: 58.3, strength: 1.32 },
  // monsters
  godzilla: { win: 64.2, strength: 1.567 },
  kingkong: { win: 40.8, strength: 0.749 },
  alien: { win: 55.9, strength: 1.2 },
  predator: { win: 46.7, strength: 0.9 },
  trex: { win: 43.3, strength: 0.811 },
  jaws: { win: 49.2, strength: 0.973 },
  // action
  johnwick: { win: 54.8, strength: 1.167 },
  neo: { win: 50, strength: 1 },
  terminator: { win: 47.1, strength: 0.908 },
  robocop: { win: 47.1, strength: 0.908 },
  indianajones: { win: 48.8, strength: 0.962 },
  jamesbond: { win: 53, strength: 1.101 },
  rambo: { win: 50.6, strength: 1.019 },
  jacksparrow: { win: 48.8, strength: 0.962 },
  // tv
  homelander: { win: 59.4, strength: 1.366 },
  omniman: { win: 46.9, strength: 0.902 },
  aang: { win: 45.9, strength: 0.871 },
  zuko: { win: 47.9, strength: 0.933 },
  jonsnow: { win: 52.1, strength: 1.071 },
  nightking: { win: 46.4, strength: 0.886 },
  walterwhite: { win: 55.8, strength: 1.209 },
  eleven: { win: 50, strength: 1 },
  daenerys: { win: 45.9, strength: 0.871 },
  // pokemon
  pikachu: { win: 54.2, strength: 1.143 },
  charizard: { win: 52.8, strength: 1.093 },
  mewtwo: { win: 41, strength: 0.749 },
  lucario: { win: 51.4, strength: 1.046 },
  greninja: { win: 42.4, strength: 0.783 },
  gengar: { win: 51.4, strength: 1.046 },
  snorlax: { win: 57, strength: 1.249 },
  // modernAnime
  gojo: { win: 51.8, strength: 1.06 },
  sukuna: { win: 50, strength: 1 },
  tanjiro: { win: 44.1, strength: 0.824 },
  nezuko: { win: 52.4, strength: 1.08 },
  levi: { win: 51.2, strength: 1.039 },
  eren: { win: 48.3, strength: 0.944 },
  deku: { win: 48.8, strength: 0.962 },
  bakugo: { win: 53.6, strength: 1.123 },
  // sandbox
  steve: { win: 58.3, strength: 1.309 },
  creeper: { win: 54.2, strength: 1.144 },
  enderman: { win: 50, strength: 1.001 },
  jonesy: { win: 54.2, strength: 1.144 },
  peely: { win: 41.7, strength: 0.765 },
  noob: { win: 54.2, strength: 1.144 },
  crewmate: { win: 37.5, strength: 0.667 },
  // horror
  freddy: { win: 52.8, strength: 1.092 },
  jason: { win: 45.8, strength: 0.876 },
  michaelmyers: { win: 57, strength: 1.248 },
  ghostface: { win: 50, strength: 1 },
  pennywise: { win: 44.5, strength: 0.838 },
  chucky: { win: 48.6, strength: 0.957 },
  leatherface: { win: 51.4, strength: 1.045 },
  // animated
  buzz: { win: 49.3, strength: 0.977 },
  woody: { win: 47.2, strength: 0.915 },
  shrek: { win: 45.9, strength: 0.875 },
  pussinboots: { win: 47.2, strength: 0.915 },
  toothless: { win: 62.5, strength: 1.496 },
  elsa: { win: 50.7, strength: 1.022 },
  mrincredible: { win: 47.3, strength: 0.915 },
  // cartoons
  homer: { win: 57, strength: 1.253 },
  spongebob: { win: 35.4, strength: 0.62 },
  rick: { win: 52.8, strength: 1.095 },
  bugsbunny: { win: 61.1, strength: 1.437 },
  tom: { win: 49.4, strength: 0.979 },
  jerry: { win: 54.2, strength: 1.145 },
  popeye: { win: 40.2, strength: 0.73 },
};
