import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – Action movies. --- fl-overhaul --- (Stage 2: one exported FlFighterRow[] per division, at most 10 rows;
 * the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

export const FL_ROWS_ACTION: readonly FlFighterRow[] = [
  {
    id: "johnwick",
    name: "John Wick",
    division: "action",
    source: "John Wick (movies)",
    body: "#1f2937",
    accent: "#e5e7eb",
    weapons: [{ kind: "gun", shape: "bullet", cooldown: 0.7, damage: 5.5, spread: 0.5, look: "pistol" }],
    stats: S({ speed: 1.15, damage: 0.58 }),
    ability: { name: "Baba Yaga", charge: 9, effects: [{ p: "giantHit", mult: 2, count: 5, homing: 4 }] },
    description: "Precise pistols; Baba Yaga makes his next five shots double and homing.",
    role: "ranged",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "neo",
    name: "Neo",
    division: "action",
    source: "The Matrix (movies)",
    body: "#0b0f0b",
    accent: "#22c55e",
    weapons: [{ kind: "fists", cooldown: 0.4, damage: 5.5, reach: 1.0 }],
    stats: S({ hp: 95, speed: 1.3, damage: 0.88, size: 0.9 }),
    ability: { name: "Bullet Time", charge: 11, effects: [{ p: "slowTime", dur: 2.5, factor: 0.3 }] },
    description: "Fast martial arts; Bullet Time slows every foe and every shot to a crawl while he moves at full speed.",
    role: "glass",
    isNew: false,
    look: { pattern: "visor", crest: "none", trail: "#22c55e" },
  },
  {
    id: "terminator",
    name: "Terminator",
    division: "action",
    source: "The Terminator (movies)",
    body: "#27272a",
    accent: "#dc2626",
    weapons: [{ kind: "shotgun", count: 6, damage: 2.8, cooldown: 1.6 }],
    stats: S({ hp: 120, speed: 0.85, damage: 0.82, size: 1.1 }),
    ability: { name: "Minigun", charge: 11, effects: [{ p: "volley", n: 12, damage: 2.5, spread: 40, speed: 1.7, shape: "bullet" }] },
    description: "A shotgun and a lot of armour; the Minigun fires twelve bullets at once.",
    role: "tank",
    isNew: false,
    look: { pattern: "band", crest: "none" },
  },
  {
    id: "robocop",
    name: "RoboCop",
    division: "action",
    source: "RoboCop (movies)",
    body: "#a5b4c8",
    accent: "#334155",
    weapons: [{ kind: "gun", style: "burst", count: 3, cooldown: 1.5, damage: 3.2, speed: 1.6, spread: 4, look: "pistol" }],
    stats: S({ hp: 115, speed: 0.8, damage: 0.93, size: 1.1 }),
    ability: { name: "Targeting", charge: 9, effects: [{ p: "giantHit", mult: 1, count: 9, homing: 5 }] },
    description: "The Auto-9 fires three-round bursts; Targeting makes his next nine shots home in.",
    role: "tank",
    isNew: false,
    look: { pattern: "visor", crest: "none" },
  },
  {
    id: "indianajones",
    name: "Indiana Jones",
    short: "INDY",
    division: "action",
    source: "Indiana Jones (movies)",
    body: "#92400e",
    accent: "#d6b48a",
    weapons: [{ kind: "whip", reach: 2.8, cooldown: 0.8, damage: 6, color: "#78350f" }],
    stats: S({ damage: 1.85 }),
    ability: { name: "Rolling Boulder", charge: 10, effects: [{ p: "volley", n: 1, damage: 18, speed: 0.75, size: 1.1, shape: "boulder", knockback: 3, pierce: true, color: "#78716c" }] },
    description: "A whip that cracks across half the ring; the Rolling Boulder flattens whoever stands in its way.",
    role: "duelist",
    isNew: true,
    look: { pattern: "band", crest: "halo" },
  },
  {
    id: "jamesbond",
    name: "James Bond",
    division: "action",
    source: "James Bond (movies)",
    body: "#111827",
    accent: "#e5e7eb",
    weapons: [{ kind: "gun", cooldown: 0.8, damage: 5.5, spread: 0, speed: 1.7, look: "pistol" }],
    stats: S({ damage: 0.81 }),
    ability: { name: "Laser Watch", charge: 9, effects: [{ p: "beam", dur: 0.8, width: 0.4, damage: 10, color: "#ef4444" }] },
    description: "A precise pistol; the Laser Watch cuts a thin red ray at the nearest foe.",
    role: "ranged",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "rambo",
    name: "Rambo",
    division: "action",
    source: "Rambo (movies)",
    body: "#3f6212",
    accent: "#b91c1c",
    weapons: [{ kind: "bow", cooldown: 1.2, damage: 8, speed: 1.6 }],
    stats: S({ hp: 105, damage: 0.81 }),
    ability: { name: "Booby Trap", charge: 9, effects: [{ p: "trap", n: 2, damage: 14, hold: 0.8, dur: 8, shape: "jaws" }] },
    description: "A compound bow; Booby Trap hides two traps that snap shut on whoever runs over them.",
    role: "control",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "jacksparrow",
    name: "Jack Sparrow",
    short: "SPARROW",
    division: "action",
    source: "Pirates of the Caribbean (movies)",
    body: "#7c2d12",
    accent: "#b91c1c",
    weapons: [
      { kind: "sword", cooldown: 0.38, damage: 6, look: "blade", color: "#e5e7eb" },
      { kind: "gun", cooldown: 3, damage: 9, speed: 1.2, spread: 3, look: "pistol" },
    ],
    stats: S({ speed: 1.1, damage: 0.83 }),
    ability: { name: "Broadside", charge: 9, effects: [{ p: "volley", n: 5, damage: 5, spread: 60, speed: 1.1, size: 0.35, shape: "cannonball", color: "#1f2937" }] },
    description: "A cutlass and a one-shot flintlock; the Broadside fires five cannonballs across the ring.",
    role: "duelist",
    isNew: true,
    look: { pattern: "band", crest: "points" },
  },
];
