import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – Animated movies (Pixar, DreamWorks, Disney). --- fl-overhaul --- (Stage 2: a new division; one exported
 * FlFighterRow[] per division, at most 10 rows; the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

export const FL_ROWS_ANIMATED: readonly FlFighterRow[] = [
  {
    id: "buzz",
    name: "Buzz Lightyear",
    short: "BUZZ",
    division: "animated",
    source: "Toy Story (animated movies)",
    body: "#f8fafc",
    accent: "#7c3aed",
    weapons: [{ kind: "beam", cooldown: 1.6, damage: 6, color: "#ef4444" }],
    stats: S({ damage: 1.71 }),
    ability: { name: "Karate Chop Action", charge: 9, effects: [{ p: "giantHit", mult: 3, knockback: 2 }] },
    description: "A wrist laser at range; Karate Chop Action makes his next hit triple.",
    role: "ranged",
    isNew: true,
    look: { pattern: "ring", crest: "points" },
  },
  {
    id: "woody",
    name: "Woody",
    division: "animated",
    source: "Toy Story (animated movies)",
    body: "#facc15",
    accent: "#92400e",
    weapons: [{ kind: "whip", style: "lasso", reach: 2.8, cooldown: 1.6, damage: 4, shape: "lasso", color: "#a16207" }],
    stats: S({ damage: 1.84 }),
    ability: { name: "Bullseye", charge: 9, effects: [{ p: "summon", n: 1, dur: 4, damage: 7, size: 0.75, speed: 1.6, shape: "horse" }] },
    description: "A lasso that ropes the foe in; Bullseye, his horse, gallops in to trample for four seconds.",
    role: "summoner",
    isNew: true,
    look: { pattern: "band", crest: "halo" },
  },
  {
    id: "shrek",
    name: "Shrek",
    division: "animated",
    source: "Shrek (animated movies)",
    body: "#65a30d",
    accent: "#a16207",
    weapons: [{ kind: "fists", cooldown: 1.0, damage: 11, knockback: 1.8, size: 0.5 }],
    stats: S({ hp: 120, speed: 0.85, size: 1.15, damage: 0.76 }),
    ability: { name: "Ogre Roar", charge: 11, effects: [{ p: "shockwave", radius: 5, damage: 8, knockback: 3.5 }] },
    description: "Big swampy fists; the Ogre Roar blows every foe across the ring.",
    role: "tank",
    isNew: true,
    look: { pattern: "band", crest: "horns" },
  },
  {
    id: "pussinboots",
    name: "Puss in Boots",
    short: "PUSS",
    division: "animated",
    source: "Shrek (animated movies)",
    body: "#f59e0b",
    accent: "#78350f",
    weapons: [{ kind: "sword", cooldown: 0.28, reach: 1.6, damage: 4.5, look: "rapier", color: "#e5e7eb" }],
    stats: S({ hp: 90, speed: 1.4, size: 0.75, damage: 1.83 }),
    ability: { name: "Big Eyes", charge: 9, effects: [{ p: "disarm", dur: 3 }] },
    description: "A quick rapier; Big Eyes melts the nearest foe so it cannot attack for three seconds.",
    role: "glass",
    isNew: true,
    look: { pattern: "band", crest: "ears" },
  },
  {
    id: "toothless",
    name: "Toothless",
    division: "animated",
    source: "How to Train Your Dragon (animated movies)",
    body: "#111827",
    accent: "#a78bfa",
    weapons: [{ kind: "gun", shape: "plasma", cooldown: 1.3, damage: 7, speed: 1.4, size: 0.3, color: "#a78bfa" }],
    stats: S({ speed: 1.2, damage: 0.86 }),
    ability: { name: "Plasma Blast", charge: 10, effects: [{ p: "volley", n: 1, damage: 18, speed: 1.1, size: 0.6, shape: "plasma", explode: 3.5, color: "#a78bfa" }] },
    description: "Fast plasma shots; his Plasma Blast is one huge bolt that explodes on impact.",
    role: "ranged",
    isNew: true,
    look: { pattern: "core", crest: "fins", glow: "#a78bfa" },
  },
  {
    id: "elsa",
    name: "Elsa",
    division: "animated",
    source: "Frozen (animated movies)",
    body: "#bae6fd",
    accent: "#e0f2fe",
    weapons: [{ kind: "ice", cooldown: 1.8, damage: 5, effect: 1 }],
    stats: S({ damage: 2.14 }),
    ability: { name: "Eternal Winter", charge: 12, effects: [{ p: "freezeAll", dur: 1.5 }] },
    description: "Ice shots freeze whoever they hit; Eternal Winter freezes every foe at once.",
    role: "control",
    isNew: true,
    look: { pattern: "ring", crest: "tuft", glow: "#bae6fd" },
  },
  {
    id: "mrincredible",
    name: "Mr. Incredible",
    short: "INCREDIBLE",
    division: "animated",
    source: "The Incredibles (animated movies)",
    body: "#dc2626",
    accent: "#111827",
    weapons: [{ kind: "fists", cooldown: 0.85, damage: 10, knockback: 1.7, size: 0.48 }],
    stats: S({ hp: 115, speed: 0.85, size: 1.1, damage: 0.86 }),
    ability: { name: "Car Throw", charge: 10, effects: [{ p: "volley", n: 1, damage: 16, speed: 1.0, size: 0.9, shape: "car", knockback: 3, color: "#dc2626" }] },
    description: "Super-strong punches; the Car Throw hurls something huge at the nearest foe.",
    role: "tank",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
];
