import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – DC (comics & movies). --- fl-overhaul --- (Stage 2: one exported FlFighterRow[] per division, at most
 * 10 rows; the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

const DC = "DC (comics & movies)";

export const FL_ROWS_DC: readonly FlFighterRow[] = [
  {
    id: "superman",
    name: "Superman",
    division: "dc",
    source: DC,
    body: "#1d4ed8",
    accent: "#dc2626",
    weapons: [{ kind: "beam", cooldown: 2.0, damage: 9, color: "#ef4444" }],
    stats: S({ hp: 105, damage: 1.32 }),
    ability: { name: "Solar Flare", charge: 12, effects: [{ p: "shockwave", radius: 5, damage: 22, knockback: 1.5 }] },
    description: "Heat vision: a thin red ray at the nearest foe every two seconds; Solar Flare is a shockwave of heavy damage.",
    role: "ranged",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "batman",
    name: "Batman",
    division: "dc",
    source: DC,
    body: "#374151",
    accent: "#facc15",
    weapons: [{ kind: "cards", shape: "batarang", count: 3, cooldown: 1.0, damage: 6 }],
    stats: S({ damage: 0.95 }),
    ability: {
      name: "Smoke Bomb",
      charge: 10,
      effects: [
        { p: "invulnerable", dur: 2 },
        { p: "giantHit", mult: 3 },
      ],
    },
    description: "Batarangs circle him and fly at the foe; Smoke Bomb makes him untouchable for two seconds and his next hit triple.",
    role: "duelist",
    isNew: false,
    look: { pattern: "visor", crest: "points" },
  },
  {
    id: "joker",
    name: "Joker",
    division: "dc",
    source: DC,
    body: "#7e22ce",
    accent: "#22c55e",
    weapons: [{ kind: "cards", shape: "card", count: 4, cooldown: 0.9, damage: 5 }],
    stats: S({ speed: 1.05, damage: 1.34 }),
    ability: { name: "Laughing Gas", charge: 9, effects: [{ p: "confuse", dur: 2.5 }] },
    description: "Razor cards orbit him and fly one by one; Laughing Gas slows every foe and turns its aim backwards.",
    role: "control",
    isNew: false,
    look: { pattern: "stripes", crest: "tuft" },
  },
  {
    id: "wonderwoman",
    name: "Wonder Woman",
    short: "WONDER",
    division: "dc",
    source: DC,
    body: "#b91c1c",
    accent: "#fbbf24",
    weapons: [{ kind: "sword", damage: 8, look: "blade" }, { kind: "shield", style: "block", size: 0.5 }],
    stats: S({ speed: 1.05, damage: 0.57 }),
    ability: {
      name: "Lasso of Truth",
      charge: 9,
      effects: [
        { p: "pull", strength: 2.2 },
        { p: "choke", dur: 1, damage: 4 },
      ],
    },
    description: "A sword, and bracelets that block hits from the front; the Lasso of Truth pulls the nearest foe in and holds it.",
    role: "duelist",
    isNew: false,
    look: { pattern: "band", crest: "none" },
  },
  {
    id: "flash",
    name: "The Flash",
    short: "FLASH",
    division: "dc",
    source: DC,
    body: "#b91c1c",
    accent: "#facc15",
    weapons: [{ kind: "fists", style: "contact", reach: 0.15, cooldown: 0.3, damage: 4, size: 0.3 }],
    stats: S({ hp: 90, speed: 1.7, size: 0.9, damage: 1.45 }),
    ability: { name: "Speed Force", charge: 11, effects: [{ p: "slowTime", dur: 2.5, factor: 0.35 }] },
    description: "Hits by running straight through you; the Speed Force slows every foe and every shot while he keeps full speed.",
    role: "glass",
    isNew: true,
    look: { pattern: "ring", crest: "none", trail: "#facc15" },
  },
  {
    id: "aquaman",
    name: "Aquaman",
    division: "dc",
    source: DC,
    body: "#f59e0b",
    accent: "#15803d",
    weapons: [{ kind: "sword", reach: 2.0, cooldown: 0.5, damage: 9, look: "trident", color: "#fbbf24" }],
    stats: S({ hp: 110, damage: 0.8 }),
    ability: { name: "Marine Telepathy", charge: 9, effects: [{ p: "summon", n: 2, dur: 4, damage: 5, size: 0.6, shape: "shark" }] },
    description: "A long trident keeps foes at a distance; Marine Telepathy calls two sharks into the ring.",
    role: "summoner",
    isNew: true,
    look: { pattern: "dots", crest: "none" },
  },
  {
    id: "harleyquinn",
    name: "Harley Quinn",
    short: "HARLEY",
    division: "dc",
    source: DC,
    body: "#dc2626",
    accent: "#1f2937",
    weapons: [{ kind: "hammer", cooldown: 1.2, damage: 9, knockback: 1.6, look: "mallet", shape: "mallet" }],
    stats: S({ speed: 1.15, damage: 1.41 }),
    ability: { name: "Bud and Lou", charge: 9, effects: [{ p: "summon", n: 2, dur: 4, damage: 5, size: 0.6, shape: "hyena" }] },
    description: "A giant mallet swung in fast circles; Bud and Lou, her two hyenas, join the brawl.",
    role: "summoner",
    isNew: true,
    look: { pattern: "split", crest: "tuft" },
  },
  {
    id: "darkseid",
    name: "Darkseid",
    division: "dc",
    source: DC,
    body: "#4b5563",
    accent: "#ef4444",
    weapons: [{ kind: "beam", cooldown: 2.4, damage: 10, color: "#ef4444" }],
    stats: S({ hp: 125, speed: 0.8, size: 1.15, damage: 1.37 }),
    ability: { name: "Omega Effect", charge: 10, effects: [{ p: "volley", n: 2, damage: 9, speed: 1.1, spread: 30, homing: 2, bounceFoes: true, shape: "bolt", color: "#ef4444" }] },
    description: "Slow and armoured, his Omega Beams curve toward the foe; the Omega Effect bounces between every rival.",
    role: "tank",
    isNew: true,
    look: { pattern: "band", crest: "none", glow: "#ef4444" },
  },
];
