import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – Fantasy (Harry Potter, The Lord of the Rings, The Witcher). --- fl-overhaul --- (Stage 2: one exported
 * FlFighterRow[] per division, at most 10 rows; the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

const HP = "Harry Potter (movies & books)";
const LOTR = "The Lord of the Rings (movies & books)";

export const FL_ROWS_FANTASY: readonly FlFighterRow[] = [
  {
    id: "harrypotter",
    name: "Harry Potter",
    short: "HARRY",
    division: "fantasy",
    source: HP,
    body: "#991b1b",
    accent: "#fbbf24",
    weapons: [{ kind: "wand", cooldown: 1.0, damage: 5, color: "#fca5a5" }],
    stats: S({ speed: 1.05, damage: 1.01 }),
    ability: { name: "Expelliarmus", charge: 9, effects: [{ p: "disarm", dur: 3 }] },
    description: "Fast bolts from his wand; Expelliarmus disarms the nearest foe for three seconds.",
    role: "control",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "voldemort",
    name: "Voldemort",
    division: "fantasy",
    source: HP,
    body: "#1f2937",
    accent: "#4ade80",
    weapons: [{ kind: "wand", cooldown: 1.45, damage: 8, color: "#86efac" }],
    stats: S({ damage: 1.13 }),
    ability: { name: "Avada Kedavra", charge: 13, ultimate: true, effects: [{ p: "volley", n: 1, damage: 30, speed: 1.6, size: 0.3, shape: "bolt", color: "#22c55e", unblockable: true }] },
    description: "Stronger, slower bolts; Avada Kedavra is one unblockable bolt at nearly four times the damage.",
    role: "ranged",
    isNew: false,
    look: { pattern: "hood", crest: "none" },
  },
  {
    id: "gandalf",
    name: "Gandalf",
    division: "fantasy",
    source: LOTR,
    body: "#a8a29e",
    accent: "#f5f5f4",
    weapons: [
      { kind: "staff", cooldown: 2.3, damage: 8, color: "#fef9c3" },
      { kind: "sword", damage: 6, reach: 1.6, color: "#e5e7eb", look: "blade" },
    ],
    stats: S({ damage: 0.94 }),
    ability: {
      name: "You Shall Not Pass",
      charge: 12,
      effects: [
        { p: "invulnerable", dur: 2 },
        { p: "shockwave", radius: 6, damage: 8, knockback: 3.5, pin: true },
      ],
    },
    description: "A staff of homing orbs and a sword; You Shall Not Pass makes him untouchable and pins every foe to the far wall.",
    role: "control",
    isNew: false,
    look: { pattern: "hood", crest: "points" },
  },
  {
    id: "legolas",
    name: "Legolas",
    division: "fantasy",
    source: LOTR,
    body: "#4d7c0f",
    accent: "#fde68a",
    weapons: [{ kind: "bow", cooldown: 0.55, damage: 4, speed: 1.5 }],
    stats: S({ hp: 95, speed: 1.3, damage: 0.99, size: 0.9 }),
    ability: { name: "Arrow Storm", charge: 11, effects: [{ p: "volley", n: 12, damage: 3, spread: 50, speed: 1.4, shape: "arrow" }] },
    description: "The fastest bow in the league; Arrow Storm looses twelve arrows at once.",
    role: "glass",
    isNew: false,
    look: { pattern: "band", crest: "points" },
  },
  {
    id: "hermione",
    name: "Hermione Granger",
    short: "HERMIONE",
    division: "fantasy",
    source: HP,
    body: "#7f1d1d",
    accent: "#fbbf24",
    weapons: [{ kind: "wand", cooldown: 0.9, damage: 4.5, spread: 0.5, color: "#fde68a" }],
    stats: S({ hp: 95, speed: 1.1, damage: 1.09 }),
    ability: { name: "Petrificus Totalus", charge: 9, effects: [{ p: "choke", dur: 2.2, damage: 0 }] },
    description: "Quick, accurate spells; Petrificus Totalus binds the nearest foe stiff for two seconds.",
    role: "control",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "dumbledore",
    name: "Dumbledore",
    division: "fantasy",
    source: HP,
    body: "#6d28d9",
    accent: "#e5e7eb",
    weapons: [{ kind: "wand", cooldown: 1.3, damage: 7, homing: 0.8, color: "#c4b5fd" }],
    stats: S({ hp: 95, damage: 1.08 }),
    ability: { name: "Firestorm", charge: 11, effects: [{ p: "fireRing", radius: 3.5, damage: 6, dur: 2.5 }] },
    description: "The Elder Wand's heavy bolts curve toward the foe; Firestorm wraps him in a whirl of fire.",
    role: "ranged",
    isNew: true,
    look: { pattern: "hood", crest: "points" },
  },
  {
    id: "aragorn",
    name: "Aragorn",
    division: "fantasy",
    source: LOTR,
    body: "#3f3f46",
    accent: "#4ade80",
    weapons: [{ kind: "sword", reach: 2.0, damage: 8, color: "#e5e7eb", look: "blade" }],
    stats: S({ damage: 0.74 }),
    ability: { name: "Army of the Dead", charge: 9, effects: [{ p: "summon", n: 3, dur: 4, damage: 4, size: 0.55, shape: "ghost" }] },
    description: "A ranger's longsword; the Army of the Dead rides in to fight beside him for four seconds.",
    role: "summoner",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "sauron",
    name: "Sauron",
    division: "fantasy",
    source: LOTR,
    body: "#1c1917",
    accent: "#f97316",
    weapons: [{ kind: "hammer", cooldown: 2.0, reach: 1.8, damage: 14, knockback: 2.2, look: "block" }],
    stats: S({ hp: 125, speed: 0.8, size: 1.15, damage: 1.22 }),
    ability: { name: "Eye of Sauron", charge: 10, effects: [{ p: "beam", dur: 1.5, width: 0.9, damage: 6, color: "#f97316" }] },
    description: "A huge mace sweeps foes aside; the Eye of Sauron fixes them with a burning ray.",
    role: "tank",
    isNew: true,
    look: { pattern: "band", crest: "spikes" },
  },
  {
    id: "geralt",
    name: "Geralt",
    division: "fantasy",
    source: "The Witcher (games & books)",
    body: "#e5e7eb",
    accent: "#78716c",
    weapons: [{ kind: "sword", reach: 2.0, cooldown: 0.34, damage: 8, color: "#e2e8f0", look: "blade" }],
    stats: S({ damage: 0.94 }),
    ability: { name: "Aard", charge: 11, effects: [{ p: "shockwave", radius: 5, damage: 6, knockback: 3 }] },
    description: "Swift silver-sword cuts; the Aard sign blasts every foe away from him.",
    role: "duelist",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
];
