import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – League of Legends (video game). --- fl-overhaul --- (Stage 2: one exported FlFighterRow[] per division,
 * at most 10 rows; the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

const LEAGUE = "League of Legends (video game)";

export const FL_ROWS_LEAGUE: readonly FlFighterRow[] = [
  {
    id: "yuumi",
    name: "Yuumi",
    division: "league",
    source: LEAGUE,
    body: "#f5f0e6",
    accent: "#6366f1",
    weapons: [{ kind: "book", cooldown: 1.5, damage: 6 }],
    stats: S({ damage: 1.14, size: 0.9 }),
    ability: { name: "Final Chapter", charge: 10, effects: [{ p: "beam", dur: 2, width: 0.8, damage: 5, color: "#c4b5fd" }] },
    description: "Her book fires slow homing bolts; Final Chapter turns its pages into a beam that lasts two seconds.",
    role: "support",
    isNew: false,
    look: { pattern: "core", crest: "ears" },
  },
  {
    id: "katarina",
    name: "Katarina",
    division: "league",
    source: LEAGUE,
    body: "#9f1239",
    accent: "#f43f5e",
    weapons: [{ kind: "cards", style: "blink", shape: "dagger", count: 3, cooldown: 0.8, damage: 6 }],
    stats: S({ hp: 95, speed: 1.3, damage: 0.61, size: 0.9 }),
    ability: { name: "Death Lotus", charge: 9, effects: [{ p: "fireRing", radius: 3, damage: 5, dur: 2.5, shape: "blades" }] },
    description: "Throws daggers and blinks to every third one she throws; Death Lotus spins a ring of blades around her.",
    role: "glass",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "garen",
    name: "Garen",
    division: "league",
    source: LEAGUE,
    body: "#1e40af",
    accent: "#eab308",
    weapons: [{ kind: "sword", damage: 9, reach: 2.0, color: "#e5e7eb", look: "greatsword" }],
    stats: S({ hp: 115, speed: 0.85, damage: 0.48, size: 1.1 }),
    ability: { name: "Demacian Justice", charge: 9, effects: [{ p: "giantHit", mult: 2, belowHalf: 4 }] },
    description: "A broad sword and thick armour; Demacian Justice quadruples his next hit on a foe below half its HP.",
    role: "tank",
    isNew: false,
    look: { pattern: "band", crest: "none" },
  },
  {
    id: "jinx",
    name: "Jinx",
    division: "league",
    source: LEAGUE,
    body: "#3b82f6",
    accent: "#ec4899",
    weapons: [{ kind: "gun", shape: "bullet", cooldown: 0.2, damage: 1.6, spread: 12, speed: 1.6, look: "minigun" }],
    stats: S({ hp: 95, damage: 0.8 }),
    ability: { name: "Super Mega Death Rocket", charge: 10, effects: [{ p: "volley", n: 1, damage: 14, speed: 0.9, size: 0.45, shape: "rocket", explode: 4 }] },
    description: "Her minigun sprays fast, weak bullets; the Super Mega Death Rocket explodes in a shockwave where it lands.",
    role: "ranged",
    isNew: false,
    look: { pattern: "stripes", crest: "tuft" },
  },
  {
    id: "ahri",
    name: "Ahri",
    division: "league",
    source: LEAGUE,
    body: "#fbcfe8",
    accent: "#be123c",
    weapons: [{ kind: "staff", style: "return", reach: 0.5, cooldown: 1.8, damage: 7, speed: 0.9, homing: 0.6, color: "#f9a8d4" }],
    stats: S({ speed: 1.1, damage: 1 }),
    ability: { name: "Spirit Rush", charge: 10, effects: [{ p: "blinkStrike", n: 3, damage: 7 }] },
    description: "Orbs fly out, hit on the way and come back to her; Spirit Rush dashes onto the nearest foe three times.",
    role: "ranged",
    isNew: false,
    look: { pattern: "core", crest: "ears" },
  },
  {
    id: "lux",
    name: "Lux",
    division: "league",
    source: LEAGUE,
    body: "#fde68a",
    accent: "#e0f2fe",
    weapons: [{ kind: "wand", cooldown: 1.0, damage: 5, speed: 2.2, color: "#fef08a" }],
    stats: S({ hp: 95, damage: 0.89 }),
    ability: { name: "Final Spark", charge: 11, effects: [{ p: "beam", dur: 1, width: 1.3, damage: 8, color: "#fef9c3" }] },
    description: "Fires quick bolts of light; Final Spark is a laser that crosses the whole ring.",
    role: "ranged",
    isNew: true,
    look: { pattern: "ring", crest: "halo", glow: "#fde68a" },
  },
  {
    id: "yasuo",
    name: "Yasuo",
    division: "league",
    source: LEAGUE,
    body: "#1e3a8a",
    accent: "#93c5fd",
    weapons: [{ kind: "sword", cooldown: 0.3, reach: 2.0, damage: 7, look: "katana", color: "#e2e8f0" }],
    stats: S({ speed: 1.15, damage: 0.79 }),
    ability: { name: "Wind Wall", charge: 9, effects: [{ p: "wall", length: 4, dur: 4, shape: "windwall" }] },
    description: "A quick blade; Wind Wall raises a barrier of wind that stops every projectile for four seconds.",
    role: "duelist",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "leesin",
    name: "Lee Sin",
    division: "league",
    source: LEAGUE,
    body: "#f59e0b",
    accent: "#b91c1c",
    weapons: [{ kind: "fists", shape: "kicks", cooldown: 0.4, reach: 1.0, damage: 5 }],
    stats: S({ speed: 1.15, damage: 0.84 }),
    ability: { name: "Dragon's Rage", charge: 9, effects: [{ p: "giantHit", mult: 3, knockback: 4 }] },
    description: "Fast martial arts; Dragon's Rage kicks the nearest foe across the ring at triple damage.",
    role: "duelist",
    isNew: true,
    look: { pattern: "ring", crest: "none" },
  },
];
