import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – Game legends (Halo, Doom, God of War, Tomb Raider, Final Fantasy VII, Red Dead Redemption 2, Pac-Man).
 * --- fl-overhaul --- (Stage 2: one exported FlFighterRow[] per division, at most 10 rows; the index is fightLeagueRoster.ts.
 * Steve moved to Sandbox & online games, Pikachu and Charizard to Pokémon; Zeus joins Kratos here as God of War's Zeus.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

export const FL_ROWS_LEGENDS: readonly FlFighterRow[] = [
  {
    id: "masterchief",
    name: "Master Chief",
    short: "CHIEF",
    division: "legends",
    source: "Halo (video games)",
    body: "#4d7c0f",
    accent: "#f59e0b",
    weapons: [{ kind: "gun", style: "burst", count: 3, cooldown: 1.5, damage: 3, speed: 1.7, spread: 4, look: "rifle" }],
    stats: S({ hp: 115, speed: 0.85, damage: 1.03, size: 1.1 }),
    ability: {
      name: "Spartan Charge",
      charge: 9,
      effects: [
        { p: "speedBurst", mult: 2.2, dur: 1.5 },
        { p: "giantHit", mult: 3 },
      ],
    },
    description: "A burst rifle, three shots a trigger; the Spartan Charge rushes in and triples his next hit.",
    role: "tank",
    isNew: false,
    look: { pattern: "visor", crest: "none" },
  },
  {
    id: "doomslayer",
    name: "Doom Slayer",
    short: "SLAYER",
    division: "legends",
    source: "Doom (video games)",
    body: "#3f6212",
    accent: "#b91c1c",
    weapons: [{ kind: "shotgun", count: 6, spread: 32, damage: 2.6, cooldown: 1.5 }],
    stats: S({ hp: 105, damage: 0.97 }),
    ability: { name: "BFG", charge: 12, effects: [{ p: "beam", dur: 1, width: 1.6, damage: 10, color: "#4ade80" }] },
    description: "A shotgun cone of pellets at close range; the BFG fires a wide green beam.",
    role: "bruiser",
    isNew: false,
    look: { pattern: "visor", crest: "none" },
  },
  {
    id: "kratos",
    name: "Kratos",
    division: "legends",
    source: "God of War (video games)",
    body: "#e5e7eb",
    accent: "#b91c1c",
    weapons: [{ kind: "chain", shape: "blades", reach: 2.3, cooldown: 1.2, damage: 8 }],
    stats: S({ damage: 1.59 }),
    ability: {
      name: "Spartan Rage",
      charge: 10,
      effects: [
        { p: "damageBurst", mult: 2, dur: 3 },
        { p: "heal", amount: 20, dur: 3 },
      ],
    },
    description: "The Blades of Chaos whirl on their chains; Spartan Rage doubles his damage and heals 20 HP over three seconds.",
    role: "bruiser",
    isNew: false,
    look: { pattern: "stripes", crest: "none" },
  },
  {
    id: "zeus",
    name: "Zeus",
    division: "legends",
    source: "God of War (video games)",
    body: "#e5e7eb",
    accent: "#facc15",
    weapons: [{ kind: "gun", shape: "bolt", cooldown: 1.2, damage: 6, speed: 1.8, spread: 1, color: "#facc15" }],
    stats: S({ hp: 110, damage: 1.02 }),
    ability: { name: "Zeus' Fury", charge: 11, effects: [{ p: "lightning", damage: 14 }] },
    description: "The king of Olympus hurls thunderbolts; Zeus' Fury strikes every foe at once.",
    role: "ranged",
    isNew: true,
    look: { pattern: "ring", crest: "halo", glow: "#facc15" },
  },
  {
    id: "laracroft",
    name: "Lara Croft",
    division: "legends",
    source: "Tomb Raider (video games)",
    body: "#0f766e",
    accent: "#92400e",
    weapons: [{ kind: "gun", style: "burst", count: 2, cooldown: 1.0, damage: 3.5, speed: 1.6, spread: 4, look: "pistol" }],
    stats: S({ speed: 1.15, damage: 0.88 }),
    ability: { name: "Survival Instinct", charge: 9, effects: [{ p: "giantHit", mult: 1.5, count: 6, homing: 4 }] },
    description: "Dual pistols in two-shot bursts; Survival Instinct makes her next six shots seek the foe and hit harder.",
    role: "ranged",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "cloud",
    name: "Cloud Strife",
    short: "CLOUD",
    division: "legends",
    source: "Final Fantasy VII (video games)",
    body: "#1e3a8a",
    accent: "#cbd5e1",
    weapons: [{ kind: "sword", reach: 2.3, cooldown: 0.55, damage: 12, knockback: 1.2, size: 0.3, look: "greatsword", color: "#cbd5e1" }],
    stats: S({ hp: 105, damage: 0.6 }),
    ability: { name: "Omnislash", charge: 10, effects: [{ p: "blinkStrike", n: 5, damage: 6 }] },
    description: "A giant sword, slow and crushing; Omnislash dashes through the nearest foe five times.",
    role: "bruiser",
    isNew: true,
    look: { pattern: "band", crest: "spikes" },
  },
  {
    id: "sephiroth",
    name: "Sephiroth",
    division: "legends",
    source: "Final Fantasy VII (video games)",
    body: "#111827",
    accent: "#e5e7eb",
    weapons: [{ kind: "sword", reach: 2.9, cooldown: 0.45, damage: 7, look: "katana", color: "#e5e7eb" }],
    stats: S({ damage: 1.1 }),
    ability: { name: "Octaslash", charge: 11, effects: [{ p: "arenaCuts", n: 8, damage: 4 }] },
    description: "The longest blade in the league; Octaslash slices the ring eight times.",
    role: "duelist",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "arthurmorgan",
    name: "Arthur Morgan",
    short: "ARTHUR",
    division: "legends",
    source: "Red Dead Redemption 2 (video game)",
    body: "#7c2d12",
    accent: "#fbbf24",
    weapons: [{ kind: "gun", cooldown: 0.9, damage: 6, spread: 0, speed: 1.7, look: "pistol" }],
    stats: S({ damage: 0.9 }),
    ability: { name: "Dead Eye", charge: 11, effects: [{ p: "slowTime", dur: 2.5, factor: 0.3 }] },
    description: "A precise revolver; Dead Eye slows every foe and every shot while he keeps firing.",
    role: "ranged",
    isNew: true,
    look: { pattern: "band", crest: "halo" },
  },
  {
    id: "pacman",
    name: "Pac-Man",
    division: "legends",
    source: "Pac-Man (video games)",
    body: "#facc15",
    accent: "#1d4ed8",
    weapons: [{ kind: "fists", style: "contact", reach: 0.15, cooldown: 0.35, damage: 4, size: 0.3 }],
    stats: S({ hp: 95, speed: 1.35, size: 0.85, damage: 0.69 }),
    ability: { name: "Power Pellet", charge: 9, effects: [{ p: "invulnerable", dur: 3, contact: 9 }] },
    description: "Chomps whatever he touches; the Power Pellet makes him invulnerable and every touch hurts.",
    role: "glass",
    isNew: true,
    look: { pattern: "ring", crest: "none" },
  },
];
