import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – Marvel (comics & movies). --- fl-overhaul --- (Stage 2: one exported FlFighterRow[] per division, at
 * most 10 rows; the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

const MARVEL = "Marvel (comics & movies)";

export const FL_ROWS_MARVEL: readonly FlFighterRow[] = [
  {
    id: "thor",
    name: "Thor",
    division: "marvel",
    source: MARVEL,
    body: "#c9ced8",
    accent: "#c1121f",
    weapons: [{ kind: "hammer", style: "returning", damage: 11, throwEvery: 3.2, look: "block" }],
    stats: S({ speed: 0.95, damage: 1.34 }),
    ability: { name: "Thunder Strike", charge: 11, effects: [{ p: "lightning", damage: 14 }] },
    description: "God of thunder: swings his hammer, throws it at the nearest foe and calls it back, then strikes every foe with lightning.",
    role: "bruiser",
    isNew: false,
    look: { pattern: "band", crest: "points", glow: "#93c5fd" },
  },
  {
    id: "loki",
    name: "Loki",
    division: "marvel",
    source: MARVEL,
    body: "#2d6a4f",
    accent: "#e9c46a",
    weapons: [{ kind: "cards", shape: "dagger", count: 4, damage: 5 }],
    stats: S({ speed: 1.1, damage: 1.34 }),
    ability: { name: "Illusion", charge: 9, effects: [{ p: "decoys", n: 2, dur: 3 }] },
    description: "The trickster: four daggers orbit him and fly one by one; Illusion conjures two decoys that soak up the hits.",
    role: "control",
    isNew: false,
    look: { pattern: "hood", crest: "horns" },
  },
  {
    id: "spiderman",
    name: "Spider-Man",
    division: "marvel",
    source: MARVEL,
    body: "#d62828",
    accent: "#1d4ed8",
    weapons: [{ kind: "web", cooldown: 0.9, damage: 5 }],
    stats: S({ hp: 95, speed: 1.3, damage: 1.06, size: 0.9 }),
    ability: { name: "Web Trap", charge: 8, effects: [{ p: "choke", dur: 2, damage: 0 }] },
    description: "Quick and slippery: web shots slow the foe they stick to, and Web Trap holds the nearest foe for two seconds.",
    role: "glass",
    isNew: false,
    look: { pattern: "split", crest: "none" },
  },
  {
    id: "ironman",
    name: "Iron Man",
    division: "marvel",
    source: MARVEL,
    body: "#b91c1c",
    accent: "#f5c518",
    weapons: [{ kind: "gun", shape: "repulsor", cooldown: 1.0, damage: 6, speed: 1.6 }],
    stats: S({ damage: 1.12 }),
    ability: { name: "Unibeam", charge: 10, effects: [{ p: "beam", dur: 1, width: 0.9, damage: 6, color: "#e0f2fe" }] },
    description: "Repulsor blasts at the nearest foe on a steady cadence; the Unibeam fires a wide ray for a second.",
    role: "ranged",
    isNew: false,
    look: { pattern: "core", crest: "none", glow: "#e0f2fe" },
  },
  {
    id: "captainamerica",
    name: "Captain America",
    short: "CAP",
    division: "marvel",
    source: MARVEL,
    body: "#1e3a8a",
    accent: "#dc2626",
    weapons: [{ kind: "shield", throwEvery: 2.5, damage: 8 }],
    stats: S({ hp: 105, damage: 1.13 }),
    ability: { name: "Shield Ricochet", charge: 9, effects: [{ p: "volley", n: 1, damage: 10, speed: 1.3, size: 0.6, shape: "shield", bounceFoes: true }] },
    description: "His shield blocks hits from the front and flies at the foe every few seconds; Shield Ricochet bounces it between every foe.",
    role: "duelist",
    isNew: false,
    look: { pattern: "ring", crest: "none" },
  },
  {
    id: "hulk",
    name: "Hulk",
    division: "marvel",
    source: MARVEL,
    body: "#4caf50",
    accent: "#6b21a8",
    weapons: [{ kind: "fists", cooldown: 1.0, damage: 12, knockback: 1.8, size: 0.5 }],
    stats: S({ hp: 115, speed: 0.85, damage: 0.88, size: 1.15 }),
    ability: { name: "Hulk Smash", charge: 11, effects: [{ p: "shockwave", radius: 4.5, damage: 14, knockback: 2.2 }] },
    description: "Big, slow and heavy: every punch hurts and knocks the foe away, and Hulk Smash sends out a shockwave.",
    role: "tank",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "venom",
    name: "Venom",
    division: "marvel",
    source: MARVEL,
    body: "#0b0b10",
    accent: "#e5e7eb",
    weapons: [{ kind: "whip", reach: 2.6, cooldown: 0.9, damage: 7, knockback: 0.7, color: "#1f2937" }],
    stats: S({ hp: 105, damage: 1.96 }),
    ability: {
      name: "Tendril Grab",
      charge: 9,
      effects: [
        { p: "pull", strength: 2.2 },
        { p: "choke", dur: 1, damage: 6 },
      ],
    },
    description: "Spider-Man's dark mirror: tendrils lash from range, and Tendril Grab drags the nearest foe in and squeezes it.",
    role: "control",
    isNew: true,
    look: { pattern: "stripes", crest: "spikes" },
  },
  {
    id: "thanos",
    name: "Thanos",
    division: "marvel",
    source: MARVEL,
    body: "#7c3aed",
    accent: "#f59e0b",
    weapons: [{ kind: "fists", cooldown: 1.1, damage: 12, knockback: 1.8, size: 0.5 }],
    stats: S({ hp: 125, speed: 0.8, size: 1.15, damage: 0.84 }),
    ability: { name: "The Snap", charge: 13, ultimate: true, effects: [{ p: "lightning", damage: 16 }] },
    description: "The Mad Titan punches like a wrecking ball, and The Snap strikes every foe at once.",
    role: "tank",
    isNew: true,
    look: { pattern: "band", crest: "none" },
  },
  {
    id: "deadpool",
    name: "Deadpool",
    division: "marvel",
    source: MARVEL,
    body: "#b91c1c",
    accent: "#111827",
    weapons: [
      { kind: "sword", style: "double", damage: 6, look: "katana", color: "#e5e7eb" },
      { kind: "gun", cooldown: 1.2, damage: 4, look: "pistol" },
    ],
    stats: S({ damage: 0.65 }),
    ability: { name: "Healing Factor", charge: 10, effects: [{ p: "heal", amount: 28, dur: 3 }] },
    description: "Two katanas and a pistol, and a Healing Factor that knits his wounds shut in three seconds.",
    role: "bruiser",
    isNew: true,
    look: { pattern: "split", crest: "none" },
  },
  {
    id: "wolverine",
    name: "Wolverine",
    division: "marvel",
    source: MARVEL,
    body: "#facc15",
    accent: "#1e3a8a",
    weapons: [{ kind: "claws", cooldown: 0.22, damage: 3, reach: 0.6 }],
    stats: S({ hp: 110, damage: 2 }),
    ability: {
      name: "Berserker Rage",
      charge: 9,
      effects: [
        { p: "attackSpeedBurst", mult: 2.5, dur: 3 },
        { p: "damageBurst", mult: 1.4, dur: 3 },
      ],
    },
    description: "Metal claws shred anything in reach; Berserker Rage turns him into a blur of slashes for three seconds.",
    role: "bruiser",
    isNew: true,
    look: { pattern: "stripes", crest: "points" },
  },
];
