import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – Modern anime (Jujutsu Kaisen, Demon Slayer, Attack on Titan, My Hero Academia). --- fl-overhaul ---
 * (Stage 2: a new division; one exported FlFighterRow[] per division, at most 10 rows; the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings (no tattoos, scars, blindfolds or muzzles). A body is a ball in a palette with one
 * of our own patterns and crests; the NAME identifies the fighter, the look only adds flavour. Names, sources and move names
 * are plain text labels of an unaffiliated fan simulation.
 */

const ANIME = (show: string) => `${show} (anime & manga)`;

export const FL_ROWS_MODERN_ANIME: readonly FlFighterRow[] = [
  {
    id: "gojo",
    name: "Gojo",
    division: "modernAnime",
    source: ANIME("Jujutsu Kaisen"),
    body: "#e5e7eb",
    accent: "#38bdf8",
    weapons: [{ kind: "staff", cooldown: 1.8, damage: 7, color: "#38bdf8" }],
    stats: S({ damage: 1.25 }),
    ability: { name: "Infinite Void", charge: 14, ultimate: true, effects: [{ p: "freezeAll", dur: 2 }] },
    description: "Blue orbs hunt the foe down; his Domain, Infinite Void, freezes every foe for two seconds.",
    role: "control",
    isNew: true,
    look: { pattern: "band", crest: "tuft", glow: "#38bdf8" },
  },
  {
    id: "sukuna",
    name: "Sukuna",
    division: "modernAnime",
    source: ANIME("Jujutsu Kaisen"),
    body: "#fca5a5",
    accent: "#111827",
    weapons: [{ kind: "claws", cooldown: 0.26, damage: 3 }],
    stats: S({ speed: 1.1, damage: 1.25 }),
    ability: { name: "Malevolent Shrine", charge: 13, ultimate: true, effects: [{ p: "arenaCuts", n: 6, damage: 6 }] },
    description: "Rapid Cleave slashes; Malevolent Shrine fills the whole ring with cuts.",
    role: "duelist",
    isNew: true,
    look: { pattern: "band", crest: "spikes" },
  },
  {
    id: "tanjiro",
    name: "Tanjiro",
    division: "modernAnime",
    source: ANIME("Demon Slayer"),
    body: "#166534",
    accent: "#f97316",
    weapons: [{ kind: "sword", cooldown: 0.34, reach: 1.9, damage: 7, look: "katana", color: "#60a5fa" }],
    stats: S({ damage: 0.51 }),
    ability: {
      name: "Hinokami Kagura",
      charge: 10,
      effects: [
        { p: "damageBurst", mult: 2, dur: 3 },
        { p: "fireRing", radius: 2.6, damage: 4, dur: 3 },
      ],
    },
    description: "Flowing swordplay; Hinokami Kagura sets his blade ablaze and doubles its damage.",
    role: "duelist",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "nezuko",
    name: "Nezuko",
    division: "modernAnime",
    source: ANIME("Demon Slayer"),
    body: "#f472b6",
    accent: "#65a30d",
    weapons: [{ kind: "fists", shape: "kicks", cooldown: 0.35, reach: 1.0, damage: 5 }],
    stats: S({ hp: 95, speed: 1.3, size: 0.85, damage: 0.7 }),
    ability: { name: "Exploding Blood", charge: 9, effects: [{ p: "fireRing", radius: 3, damage: 6, dur: 2.5 }] },
    description: "Swift kicks; Exploding Blood bursts into pink flames all around her.",
    role: "glass",
    isNew: true,
    look: { pattern: "ring", crest: "tuft" },
  },
  {
    id: "levi",
    name: "Levi",
    division: "modernAnime",
    source: ANIME("Attack on Titan"),
    body: "#1f2937",
    accent: "#15803d",
    weapons: [{ kind: "sword", style: "double", cooldown: 0.3, damage: 6, reach: 2.1, look: "double", color: "#e5e7eb" }],
    stats: S({ hp: 95, speed: 1.4, size: 0.9, damage: 0.74 }),
    ability: { name: "Spinning Slash", charge: 10, effects: [{ p: "blinkStrike", n: 5, damage: 5 }] },
    description: "Dual blades and grappling speed; the Spinning Slash zips through the nearest foe five times.",
    role: "glass",
    isNew: true,
    look: { pattern: "band", crest: "tuft", trail: "#15803d" },
  },
  {
    id: "eren",
    name: "Eren",
    division: "modernAnime",
    source: ANIME("Attack on Titan"),
    body: "#78350f",
    accent: "#15803d",
    weapons: [{ kind: "sword", style: "double", cooldown: 0.4, damage: 6, look: "double", color: "#e5e7eb" }],
    stats: S({ damage: 0.72 }),
    ability: { name: "Titan Shift", charge: 13, ultimate: true, effects: [{ p: "transform", size: 1.7, damage: 1.7, speed: 0.75, dur: 6 }] },
    description: "Dual blades, until Titan Shift turns him into a giant that hits far harder for six seconds.",
    role: "bruiser",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "deku",
    name: "Deku",
    division: "modernAnime",
    source: ANIME("My Hero Academia"),
    body: "#15803d",
    accent: "#dc2626",
    weapons: [{ kind: "fists", cooldown: 0.5, damage: 6 }],
    stats: S({ hp: 115, speed: 0.85, size: 1.1, damage: 0.64 }),
    ability: { name: "Detroit Smash", charge: 9, effects: [{ p: "giantHit", mult: 4, knockback: 3 }] },
    description: "Power-charged punches; the Detroit Smash hits four times as hard.",
    role: "tank",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "bakugo",
    name: "Bakugo",
    division: "modernAnime",
    source: ANIME("My Hero Academia"),
    body: "#111827",
    accent: "#f97316",
    weapons: [{ kind: "fire", cooldown: 1.1, reach: 2.2, damage: 4, knockback: 0.6, spread: 60 }],
    stats: S({ damage: 0.92 }),
    ability: { name: "Howitzer Impact", charge: 10, effects: [{ p: "shockwave", radius: 4, damage: 16, knockback: 1.5, spin: true }] },
    description: "Palm explosions at close range; Howitzer Impact spins into one huge blast.",
    role: "bruiser",
    isNew: true,
    look: { pattern: "band", crest: "spikes" },
  },
];
