import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – Shonen anime (Dragon Ball, Naruto, One Piece, One-Punch Man). --- fl-overhaul --- (Stage 2: one exported
 * FlFighterRow[] per division, at most 10 rows; the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

const ANIME = (show: string) => `${show} (anime & manga)`;

export const FL_ROWS_SHONEN: readonly FlFighterRow[] = [
  {
    id: "goku",
    name: "Goku",
    division: "shonen",
    source: ANIME("Dragon Ball"),
    body: "#f97316",
    accent: "#1d4ed8",
    weapons: [
      { kind: "fists", cooldown: 0.45, damage: 5 },
      { kind: "gun", shape: "ki", cooldown: 1.3, damage: 4, speed: 1.4, color: "#93c5fd" },
    ],
    stats: S({ damage: 0.68 }),
    ability: { name: "Kamehameha", charge: 10, effects: [{ p: "beam", dur: 1.2, width: 1, damage: 6, color: "#60a5fa" }] },
    description: "Fists and ki blasts; the Kamehameha is a blue beam that lasts more than a second.",
    role: "duelist",
    isNew: false,
    look: { pattern: "band", crest: "spikes" },
  },
  {
    id: "vegeta",
    name: "Vegeta",
    division: "shonen",
    source: ANIME("Dragon Ball"),
    body: "#1e3a8a",
    accent: "#facc15",
    weapons: [
      { kind: "fists", cooldown: 0.45, damage: 5.5 },
      { kind: "gun", shape: "ki", cooldown: 1.2, damage: 4, speed: 1.4, color: "#fde68a" },
    ],
    stats: S({ damage: 0.64 }),
    ability: { name: "Final Flash", charge: 13, ultimate: true, effects: [{ p: "beam", dur: 1.4, width: 1.5, damage: 7, color: "#fef08a" }] },
    description: "Fists and ki blasts; Final Flash takes longer to charge and fires a wider beam.",
    role: "duelist",
    isNew: false,
    look: { pattern: "band", crest: "spikes" },
  },
  {
    id: "naruto",
    name: "Naruto",
    division: "shonen",
    source: ANIME("Naruto"),
    body: "#fb923c",
    accent: "#1e3a8a",
    weapons: [{ kind: "cards", shape: "shuriken", count: 4, cooldown: 0.9, damage: 5 }],
    stats: S({ speed: 1.1, damage: 0.77 }),
    ability: { name: "Shadow Clone", charge: 9, effects: [{ p: "summon", n: 2, dur: 4, damage: 4, shape: "clone" }] },
    description: "Shuriken orbit him and fly one by one; Shadow Clone summons two clones that fight for four seconds.",
    role: "summoner",
    isNew: false,
    look: { pattern: "band", crest: "spikes" },
  },
  {
    id: "sasuke",
    name: "Sasuke",
    division: "shonen",
    source: ANIME("Naruto"),
    body: "#1e1b4b",
    accent: "#60a5fa",
    weapons: [{ kind: "sword", damage: 8, reach: 1.8, color: "#cbd5e1", look: "katana" }],
    stats: S({ speed: 1.15, damage: 0.63 }),
    ability: { name: "Chidori", charge: 10, effects: [{ p: "blinkStrike", n: 4, damage: 6 }] },
    description: "A quick blade; Chidori blinks onto the nearest foe four times in a row.",
    role: "duelist",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "luffy",
    name: "Luffy",
    division: "shonen",
    source: ANIME("One Piece"),
    body: "#dc2626",
    accent: "#facc15",
    weapons: [{ kind: "fists", reach: 2.2, cooldown: 0.7, damage: 6 }],
    stats: S({ damage: 0.7 }),
    ability: { name: "Gum-Gum Gatling", charge: 9, effects: [{ p: "attackSpeedBurst", mult: 4, dur: 2 }] },
    description: "Rubber fists that reach across half the ring; the Gum-Gum Gatling punches four times as fast for two seconds.",
    role: "bruiser",
    isNew: false,
    look: { pattern: "band", crest: "halo" },
  },
  {
    id: "saitama",
    name: "Saitama",
    division: "shonen",
    source: ANIME("One-Punch Man"),
    body: "#fde047",
    accent: "#ef4444",
    weapons: [{ kind: "fists", count: 1, cooldown: 1.8, damage: 18, knockback: 2 }],
    stats: S({ hp: 120, speed: 0.85, damage: 0.47, size: 1.1 }),
    ability: { name: "Serious Punch", charge: 14, ultimate: true, effects: [{ p: "giantHit", mult: 1, maxHpFrac: 0.4, knockback: 3 }] },
    description: "One slow punch at triple damage; the Serious Punch is worth 40 % of the foe's maximum HP.",
    role: "tank",
    isNew: false,
    look: { pattern: "ring", crest: "none" },
  },
  {
    id: "zoro",
    name: "Zoro",
    division: "shonen",
    source: ANIME("One Piece"),
    body: "#15803d",
    accent: "#e5e7eb",
    weapons: [{ kind: "sword", reach: 2.0, cooldown: 0.32, damage: 7, look: "katana", color: "#e5e7eb" }],
    stats: S({ damage: 0.7 }),
    ability: { name: "Oni Giri", charge: 11, effects: [{ p: "arenaCuts", n: 3, damage: 10 }] },
    description: "Three blades at once; Oni Giri cuts across the ring three times.",
    role: "duelist",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "itachi",
    name: "Itachi",
    division: "shonen",
    source: ANIME("Naruto"),
    body: "#111827",
    accent: "#dc2626",
    weapons: [{ kind: "gun", shape: "fireball", cooldown: 1.5, damage: 7, speed: 0.9, homing: 0.8, size: 0.4, spread: 0, color: "#f97316" }],
    stats: S({ hp: 90, speed: 1.3, size: 0.9, damage: 1.21 }),
    ability: { name: "Tsukuyomi", charge: 12, effects: [{ p: "freezeAll", dur: 1.5 }] },
    description: "Slow fireballs; Tsukuyomi traps every foe in an illusion that freezes them where they stand.",
    role: "glass",
    isNew: true,
    look: { pattern: "hood", crest: "none" },
  },
  {
    id: "frieza",
    name: "Frieza",
    division: "shonen",
    source: ANIME("Dragon Ball"),
    body: "#f5f3ff",
    accent: "#7e22ce",
    weapons: [{ kind: "beam", cooldown: 1.6, damage: 7, size: 0.1, color: "#a855f7" }],
    stats: S({ damage: 1.06 }),
    ability: { name: "Death Ball", charge: 13, ultimate: true, effects: [{ p: "volley", n: 1, damage: 20, speed: 0.7, size: 1.0, shape: "megaorb", explode: 4, color: "#fb923c" }] },
    description: "Pinpoint Death Beams; the Death Ball is a huge, slow sphere that explodes where it lands.",
    role: "ranged",
    isNew: true,
    look: { pattern: "core", crest: "horns" },
  },
];
