import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – Star Wars (movies & TV shows). --- fl-overhaul --- (Stage 2: one exported FlFighterRow[] per division,
 * at most 10 rows; the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

const SW = "Star Wars (movies)";
const SW_TV = "Star Wars (TV shows)";

export const FL_ROWS_STAR_WARS: readonly FlFighterRow[] = [
  {
    id: "luke",
    name: "Luke Skywalker",
    short: "LUKE",
    division: "starWars",
    source: SW,
    body: "#e7d8b8",
    accent: "#16a34a",
    weapons: [{ kind: "sword", style: "glow", damage: 8, color: "#4ade80", look: "saber" }],
    stats: S({ damage: 1.2 }),
    ability: { name: "Force Push", charge: 11, effects: [{ p: "shockwave", radius: 6, damage: 6, knockback: 3.5 }] },
    description: "A green energy blade; the Force Push throws every foe across the ring.",
    role: "duelist",
    isNew: false,
    look: { pattern: "band", crest: "none" },
  },
  {
    id: "vader",
    name: "Darth Vader",
    short: "VADER",
    division: "starWars",
    source: SW,
    body: "#111827",
    accent: "#dc2626",
    weapons: [{ kind: "sword", style: "glow", damage: 11, cooldown: 0.5, color: "#ef4444", look: "saber" }],
    stats: S({ hp: 115, speed: 0.85, damage: 0.6, size: 1.1 }),
    ability: { name: "Force Choke", charge: 10, effects: [{ p: "choke", dur: 2, damage: 15, at: "over" }] },
    description: "A red blade, slower and stronger; the Force Choke holds the nearest foe for two seconds and hurts it.",
    role: "tank",
    isNew: false,
    look: { pattern: "visor", crest: "none" },
  },
  {
    id: "yoda",
    name: "Yoda",
    division: "starWars",
    source: SW,
    body: "#84cc16",
    accent: "#a16207",
    weapons: [{ kind: "sword", style: "glow", damage: 6, reach: 1.6, color: "#86efac", look: "saber" }],
    stats: S({ hp: 95, speed: 1.45, attackSpeed: 1.3, damage: 1.09, size: 0.75 }),
    ability: { name: "Force Lift", charge: 10, effects: [{ p: "choke", dur: 2, damage: 14, at: "end" }] },
    description: "Tiny and fast with a short green blade; Force Lift holds the nearest foe up for two seconds, then slams it.",
    role: "glass",
    isNew: false,
    look: { pattern: "ring", crest: "ears" },
  },
  {
    id: "maul",
    name: "Darth Maul",
    short: "MAUL",
    division: "starWars",
    source: SW,
    body: "#b91c1c",
    accent: "#0a0a0a",
    weapons: [{ kind: "sword", style: "double", damage: 7, reach: 1.6, color: "#f87171", look: "double" }],
    stats: S({ speed: 1.1, damage: 1.48 }),
    ability: { name: "Saber Throw", charge: 9, effects: [{ p: "volley", n: 1, damage: 12, speed: 1.1, size: 0.5, shape: "saber", color: "#f87171", returning: true }] },
    description: "A double-bladed saber, a blade at both ends; the Saber Throw flies at the foe and comes back.",
    role: "duelist",
    isNew: false,
    look: { pattern: "split", crest: "horns" },
  },
  {
    id: "obiwan",
    name: "Obi-Wan Kenobi",
    short: "OBI-WAN",
    division: "starWars",
    source: SW,
    body: "#a16207",
    accent: "#60a5fa",
    weapons: [{ kind: "sword", style: "glow", damage: 7, color: "#60a5fa", look: "saber" }],
    stats: S({ damage: 1.01 }),
    ability: { name: "Soresu", charge: 9, effects: [{ p: "reflect", dur: 3, frac: 0.6, deflect: true }] },
    description: "A blue blade; Soresu, the defensive form, turns every attack back on the attacker.",
    role: "support",
    isNew: true,
    look: { pattern: "hood", crest: "none" },
  },
  {
    id: "kyloren",
    name: "Kylo Ren",
    division: "starWars",
    source: SW,
    body: "#111827",
    accent: "#ef4444",
    weapons: [{ kind: "sword", style: "glow", cooldown: 0.45, damage: 10, color: "#ef4444", look: "saber" }],
    stats: S({ hp: 105, damage: 1.13 }),
    ability: { name: "Force Freeze", charge: 12, effects: [{ p: "freezeAll", dur: 1.4 }] },
    description: "A crackling crossguard blade; Force Freeze holds every foe still in mid-air.",
    role: "bruiser",
    isNew: true,
    look: { pattern: "visor", crest: "none" },
  },
  {
    id: "palpatine",
    name: "Palpatine",
    division: "starWars",
    source: SW,
    body: "#1f2937",
    accent: "#a78bfa",
    weapons: [{ kind: "spark", reach: 2.8, cooldown: 0.7, damage: 4, color: "#a78bfa" }],
    stats: S({ hp: 95, speed: 0.9, damage: 1.9 }),
    ability: { name: "Force Storm", charge: 11, effects: [{ p: "lightning", damage: 15 }] },
    description: "Force lightning arcs at any foe in range; Force Storm strikes them all at once.",
    role: "ranged",
    isNew: true,
    look: { pattern: "hood", crest: "none", glow: "#a78bfa" },
  },
  {
    id: "mandalorian",
    name: "The Mandalorian",
    short: "MANDO",
    division: "starWars",
    source: SW_TV,
    body: "#94a3b8",
    accent: "#78350f",
    weapons: [{ kind: "gun", cooldown: 0.85, damage: 5, speed: 1.6, look: "blaster", color: "#f97316" }],
    stats: S({ hp: 110, damage: 1.07 }),
    ability: { name: "Whistling Birds", charge: 9, effects: [{ p: "volley", n: 6, damage: 3, speed: 1.2, spread: 70, size: 0.15, homing: 3, shape: "rocket" }] },
    description: "A blaster and beskar armour; Whistling Birds launches six homing mini-missiles.",
    role: "ranged",
    isNew: true,
    look: { pattern: "visor", crest: "none" },
  },
];
