import type { FlFighterRow } from "../fightLeagueRoster";
import { S } from "./kit";

/**
 * Fight League rows – TV (TV shows). --- fl-overhaul --- (Stage 2: one exported FlFighterRow[] per division, at most 10 rows;
 * the index is fightLeagueRoster.ts.)
 *
 * IP AVOID-LIST for every look in this file: no emblems, no letters, no web lines, no bat or bolt marks, no letter shields, no
 * red-white split balls, no face markings. A body is a ball in a palette with one of our own patterns and crests; the NAME
 * identifies the fighter, the look only adds flavour. Names, sources and move names are plain text labels of an
 * unaffiliated fan simulation.
 */

const GOT = "Game of Thrones (TV show)";
const AVATAR = "Avatar: The Last Airbender (TV show)";

export const FL_ROWS_TV: readonly FlFighterRow[] = [
  {
    id: "homelander",
    name: "Homelander",
    division: "tv",
    source: "The Boys (TV show)",
    body: "#1d4ed8",
    accent: "#dc2626",
    weapons: [
      { kind: "beam", cooldown: 2.2, damage: 8, color: "#ef4444" },
      { kind: "fists", cooldown: 0.55, damage: 6 },
    ],
    stats: S({ damage: 0.69 }),
    ability: { name: "Laser Sweep", charge: 10, effects: [{ p: "beam", dur: 1.5, width: 0.8, damage: 6, color: "#f87171" }] },
    description: "Laser eyes and fists; the Laser Sweep holds a red beam for a second and a half.",
    role: "ranged",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "omniman",
    name: "Omni-Man",
    division: "tv",
    source: "Invincible (TV show)",
    body: "#f8fafc",
    accent: "#dc2626",
    weapons: [{ kind: "fists", cooldown: 0.8, damage: 10, knockback: 1.8, size: 0.45 }],
    stats: S({ hp: 110, damage: 0.54 }),
    ability: {
      name: "Viltrumite Rush",
      charge: 10,
      effects: [
        { p: "speedBurst", mult: 3, dur: 2 },
        { p: "damageBurst", mult: 2, dur: 2 },
      ],
    },
    description: "Heavy fists; the Viltrumite Rush triples his speed and doubles his damage for two seconds.",
    role: "bruiser",
    isNew: false,
    look: { pattern: "band", crest: "none" },
  },
  {
    id: "aang",
    name: "Aang",
    division: "tv",
    source: AVATAR,
    body: "#f59e0b",
    accent: "#38bdf8",
    weapons: [{ kind: "fists", shape: "air", cooldown: 0.5, damage: 1.5, knockback: 2.6, reach: 1.4 }],
    stats: S({ hp: 95, speed: 1.3, damage: 1.14, castSpeed: 1.3, size: 0.85 }),
    ability: {
      name: "Avatar State",
      charge: 11,
      effects: [
        { p: "fireRing", radius: 3, damage: 6, dur: 2 },
        { p: "lightning", damage: 10 },
      ],
    },
    description: "Airbending pushes that knock foes away but barely hurt; the Avatar State is a ring of fire and a bolt of lightning.",
    role: "glass",
    isNew: false,
    look: { pattern: "band", crest: "none", glow: "#7dd3fc" },
  },
  {
    id: "zuko",
    name: "Zuko",
    division: "tv",
    source: AVATAR,
    body: "#b91c1c",
    accent: "#f59e0b",
    weapons: [{ kind: "fire", reach: 3.0, damage: 3.5 }],
    stats: S({ damage: 1.05 }),
    ability: { name: "Lightning Redirect", charge: 10, effects: [{ p: "beam", dur: 0.8, width: 0.6, damage: 10, color: "#a5f3fc" }] },
    description: "Firebending: a cone of fire ahead; Lightning Redirect fires a crackling beam.",
    role: "ranged",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "jonsnow",
    name: "Jon Snow",
    division: "tv",
    source: GOT,
    body: "#18181b",
    accent: "#e5e7eb",
    weapons: [{ kind: "sword", damage: 8.5, reach: 1.9, color: "#d4d4d8", look: "blade" }],
    stats: S({ damage: 0.62 }),
    ability: { name: "Ghost", charge: 9, effects: [{ p: "summon", n: 1, dur: 4, damage: 6, size: 0.7, shape: "wolf" }] },
    description: "A longsword; Ghost, his white wolf, joins the fight for four seconds.",
    role: "summoner",
    isNew: false,
    look: { pattern: "band", crest: "tuft" },
  },
  {
    id: "nightking",
    name: "Night King",
    division: "tv",
    source: GOT,
    body: "#93c5fd",
    accent: "#e0f2fe",
    weapons: [{ kind: "bow", shape: "icespear", cooldown: 2.0, damage: 12, speed: 0.95, size: 0.2, color: "#bae6fd" }],
    stats: S({ hp: 115, speed: 0.85, damage: 0.77, size: 1.1 }),
    ability: { name: "Raise the Dead", charge: 10, effects: [{ p: "summon", n: 3, dur: 4, damage: 4, size: 0.55, shape: "wight" }] },
    description: "Throws slow, heavy ice spears; Raise the Dead summons three wights for four seconds.",
    role: "tank",
    isNew: false,
    look: { pattern: "ring", crest: "spikes", glow: "#bae6fd" },
  },
  {
    id: "walterwhite",
    name: "Walter White",
    short: "WALTER",
    division: "tv",
    source: "Breaking Bad (TV show)",
    body: "#16a34a",
    accent: "#fde047",
    weapons: [{ kind: "bomb", cooldown: 1.5, damage: 6, effect: 1.8, shape: "flask", color: "#22c55e" }],
    stats: S({ hp: 90, damage: 2.18 }),
    ability: { name: "Fulminated Mercury", charge: 11, effects: [{ p: "shockwave", radius: 4.5, damage: 16, knockback: 2 }] },
    description: "A chemistry teacher who lobs bursting flasks; Fulminated Mercury blows up everything around him.",
    role: "ranged",
    isNew: true,
    look: { pattern: "band", crest: "halo" },
  },
  {
    id: "eleven",
    name: "Eleven",
    division: "tv",
    source: "Stranger Things (TV show)",
    body: "#f9a8d4",
    accent: "#1e40af",
    weapons: [{ kind: "spark", reach: 2.8, cooldown: 0.9, damage: 5, knockback: 0.8, color: "#f9a8d4" }],
    stats: S({ hp: 90, damage: 0.91 }),
    ability: { name: "Telekinesis", charge: 9, effects: [{ p: "choke", dur: 1.5, damage: 14, at: "end" }] },
    description: "Telekinetic pulses at any foe in range; Telekinesis lifts the nearest foe and slams it down.",
    role: "control",
    isNew: true,
    look: { pattern: "core", crest: "none" },
  },
  {
    id: "daenerys",
    name: "Daenerys Targaryen",
    short: "DAENERYS",
    division: "tv",
    source: GOT,
    body: "#f8fafc",
    accent: "#b91c1c",
    weapons: [{ kind: "fire", cooldown: 1.8, reach: 3.6, damage: 3 }],
    stats: S({ hp: 95, damage: 1.17 }),
    ability: { name: "Dracarys", charge: 12, effects: [{ p: "beam", dur: 1.4, width: 1.4, damage: 7, color: "#f97316" }] },
    description: "Her dragon breathes long cones of fire; Dracarys pours a river of flame at the nearest foe.",
    role: "ranged",
    isNew: true,
    look: { pattern: "band", crest: "tuft" },
  },
];
