import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1400, height: 1000 } });
const errs = [];
p.on("pageerror", (e) => errs.push(e.message));
await p.goto("http://localhost:4700/Balls/en/simulator/?mode=classic&inf=1&nb=50000&s=900&wc=12", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /Start Simulator/ }).click();
await p.waitForTimeout(4000);
await p.getByRole("button", { name: /Ball & Physics/ }).click();
await p.waitForTimeout(500);
await p.screenshot({ path: "/tmp/claude-0/-home-user-Balls/73cf3eb5-2fc0-57fe-bfe8-09697680a37c/scratchpad/shot1.png" });
console.log(JSON.stringify(await p.evaluate(() => ({ ...document.querySelector("main canvas").dataset }))).slice(0, 600));
await p.goto("http://localhost:4700/Balls/en/simulator/?mode=multiply&inf=1&msc=5000&s=700", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /Start Simulator/ }).click();
await p.waitForTimeout(9000);
await p.screenshot({ path: "/tmp/claude-0/-home-user-Balls/73cf3eb5-2fc0-57fe-bfe8-09697680a37c/scratchpad/shot2.png" });
const d = await p.evaluate(() => ({ ...document.querySelector("main canvas").dataset }));
console.log(Object.entries(d).filter(([k]) => k.startsWith("unlimited")).map(([k, v]) => k + "=" + v).join(" "));
console.log("errors", errs.join(" | "));
await b.close();
