import { assetPath } from "@/lib/site";

/**
 * Custom hit samples: instead of the synthesised bounce tone, every wall hit can play an
 * audio clip – one of the built-in samples in /public/hitSounds or a file the creator
 * uploaded. The pure helpers at the top (mode dispatch, playback-rate mapping, id
 * normalisation) are unit-tested; `HitSampler` is the Web Audio player that the
 * ToneGenerator owns and routes into its master gain, so recordings include the samples.
 */

export const HIT_SOUND_MODES = ["tones", "sample"] as const;
export type HitSoundMode = (typeof HIT_SOUND_MODES)[number];

export function isHitSoundMode(value: unknown): value is HitSoundMode {
  return typeof value === "string" && (HIT_SOUND_MODES as readonly string[]).includes(value);
}

export interface HitSample {
  id: string;
  /** Translation key under `Controls` for the option label. */
  nameKey: string;
  url: string;
}

/** Built-in hit samples (generated by scripts/generate-sounds.py). */
export const HIT_SAMPLES: HitSample[] = [
  { id: "click", nameKey: "hitSampleClick", url: assetPath("/hitSounds/click.wav") },
  { id: "pluck", nameKey: "hitSamplePluck", url: assetPath("/hitSounds/pluck.wav") },
  { id: "kick", nameKey: "hitSampleKick", url: assetPath("/hitSounds/kick.wav") },
];

/** `hitSampleId` value that stands for the clip uploaded in this session (kept in memory). */
export const CUSTOM_HIT_SAMPLE_ID = "custom";
export const DEFAULT_HIT_SAMPLE_ID = HIT_SAMPLES[0].id;

export function isBuiltInHitSampleId(value: unknown): value is string {
  return typeof value === "string" && HIT_SAMPLES.some((s) => s.id === value);
}

/**
 * Share links and presets can only refer to built-in samples: an uploaded clip lives in
 * memory for the current page only, so "custom" (and anything unknown) falls back to the
 * default sample. `allowCustom` keeps "custom" when the caller knows an upload exists.
 */
export function normalizeHitSampleId(value: unknown, allowCustom = false): string {
  if (isBuiltInHitSampleId(value)) return value;
  if (allowCustom && value === CUSTOM_HIT_SAMPLE_ID) return CUSTOM_HIT_SAMPLE_ID;
  return DEFAULT_HIT_SAMPLE_ID;
}

/** URL of a built-in sample, or null for "custom"/unknown ids (the caller supplies the blob URL). */
export function builtInHitSampleUrl(id: string): string | null {
  return HIT_SAMPLES.find((s) => s.id === id)?.url ?? null;
}

/**
 * Frequency of the synthesised bounce tone for a wall: 800 Hz on the innermost ring
 * (index 0), 80 Hz lower per ring, never below 300 Hz.
 */
export function wallHitFrequency(wallIndex: number): number {
  return Math.max(300, 800 - 80 * Math.max(0, Math.floor(wallIndex)));
}

/**
 * Playback rate for a hit sample on a given wall. With pitch-by-wall on, the clip follows
 * the same curve as the tones: native pitch on the innermost ring and progressively lower
 * (down to 300/800 = 0.375×) on the outer rings. Off, every wall plays the clip as recorded.
 * A hit that carries its own pitch (`frequency` in Hz – Ball Drop maps it from the ball's size)
 * plays the clip at that pitch relative to the innermost-ring tone instead.
 */
export function hitSamplePlaybackRate(wallIndex: number, pitchByWall: boolean, frequency?: number): number {
  if (!pitchByWall) return 1;
  const hz = frequency !== undefined && frequency > 0 ? frequency : wallHitFrequency(wallIndex);
  return hz / wallHitFrequency(0);
}

export type HitSoundSource = "tones" | "sample";

/** Decode state of the active clip: "loading" while it decodes, "error" when the decode failed (the tones play meanwhile). */
export type HitSampleStatus = "idle" | "loading" | "ready" | "error";

/**
 * Which path a wall hit takes. Sample mode plays the clip once it is decoded; until then
 * (or when the decode failed) the tones keep playing so a bounce is never silent.
 */
export function resolveHitSoundSource(mode: HitSoundMode, sampleReady: boolean): HitSoundSource {
  return mode === "sample" && sampleReady ? "sample" : "tones";
}

/* ------------------------------------------------------------------ player */

/** Most clips that play at once; older voices are faded out to make room. */
export const MAX_VOICES = 8;
/** Fade in/out applied to every voice (seconds) so clips never click at the edges. */
export const VOICE_FADE_SEC = 0.02;
/** Longest slice of a clip a single hit plays (seconds); keeps long uploads usable. */
export const MAX_VOICE_SEC = 5;
/** Decoded clips kept around so switching back to a sample is instant. */
const CACHE_LIMIT = 6;

interface Voice {
  source: AudioBufferSourceNode;
  gain: GainNode;
  /** --- review fix (audio) --- Context time the voice starts, its plateau level and the length of its fade in / out (seconds). */
  start: number;
  level: number;
  fade: number;
  /** --- fast-render --- Context time the voice has played out by (its `ended` event may come later, or – offline – after the whole clip is scheduled). */
  end: number;
}

// --- review fix (audio) ---
/**
 * The gain a voice's envelope has at context time `t`: 0 before it starts and after it ends, a linear ramp over the fade in
 * and the fade out, its level in between. A stolen voice fades out from this value – `AudioParam.value` only holds the last
 * rendered value (the default 1 while a fast export schedules its whole clip), so reading it made a stolen voice jump to 1.
 */
export function voiceEnvelopeAt(v: { start: number; level: number; fade: number; end: number }, t: number): number {
  if (t <= v.start || t >= v.end) return 0;
  if (v.fade > 0 && t < v.start + v.fade) return (v.level * (t - v.start)) / v.fade;
  if (v.fade > 0 && t > v.end - v.fade) return (v.level * (v.end - t)) / v.fade;
  return v.level;
}
// --- end review fix (audio) ---

export class HitSampler {
  private buffer: AudioBuffer | null = null;
  private wantedUrl: string | null = null;
  private loadedUrl: string | null = null;
  private readonly cache = new Map<string, AudioBuffer>();
  private readonly inflight = new Map<string, Promise<AudioBuffer | null>>();
  private voices: Voice[] = [];
  private volume = 1;
  private status: HitSampleStatus = "idle";
  private listener: ((status: HitSampleStatus) => void) | null = null;

  constructor(
    private readonly context: AudioContext,
    private readonly destination: AudioNode,
  ) {}

  /** True once the clip for the last `load()` call is decoded. */
  isReady(): boolean {
    return this.buffer !== null;
  }

  /** URL of the clip that is currently decoded and active, if any. */
  getLoadedUrl(): string | null {
    return this.buffer ? this.loadedUrl : null;
  }

  setVolume(volume: number) {
    this.volume = Math.max(0, Number.isFinite(volume) ? volume : 1); // --- uncap-all --- past 1 amplifies the clip
  }

  /** Decode state of the clip from the last `load()` call; a failed decode is reported as "error", never silently. */
  getStatus(): HitSampleStatus {
    return this.status;
  }

  /** Called whenever `getStatus()` changes (loading → ready / error), so the UI can show it. */
  setStatusListener(listener: ((status: HitSampleStatus) => void) | null) {
    this.listener = listener;
  }

  private setStatus(status: HitSampleStatus) {
    if (this.status === status) return;
    this.status = status;
    this.listener?.(status);
  }

  /**
   * Decodes the clip at `url` (an asset path or a blob: URL) once and makes it the active
   * sample. The previous clip keeps playing until the new one is ready. Passing null
   * clears the sample.
   */
  async load(url: string | null): Promise<void> {
    this.wantedUrl = url;
    if (!url) {
      this.buffer = null;
      this.loadedUrl = null;
      this.setStatus("idle");
      return;
    }
    const cached = this.cache.get(url);
    if (cached) {
      this.buffer = cached;
      this.loadedUrl = url;
      this.setStatus("ready");
      return;
    }
    this.setStatus("loading");
    // Repeated calls for the same clip share one fetch + decode.
    let pending = this.inflight.get(url);
    if (!pending) {
      pending = this.decode(url);
      this.inflight.set(url, pending);
    }
    const decoded = await pending;
    if (this.wantedUrl !== url) return;
    this.buffer = decoded;
    this.loadedUrl = decoded ? url : null;
    this.setStatus(decoded ? "ready" : "error");
  }

  private async decode(url: string): Promise<AudioBuffer | null> {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.arrayBuffer();
      const decoded = await this.context.decodeAudioData(data);
      this.remember(url, decoded);
      return decoded;
    } catch (err) {
      // Reported through the status ("error") so the panel can show it; the tones keep playing meanwhile.
      console.warn("Failed to decode hit sample:", err);
      return null;
    } finally {
      this.inflight.delete(url);
    }
  }

  private remember(url: string, buffer: AudioBuffer) {
    if (this.cache.size >= CACHE_LIMIT) {
      const oldest = this.cache.keys().next().value;
      if (oldest !== undefined) this.cache.delete(oldest);
    }
    this.cache.set(url, buffer);
  }

  /** Plays the active clip at `playbackRate` (at AudioContext time `when`, default now), `gainScale` × the volume (an accent plays louder); returns false when nothing is loaded. */
  play(playbackRate = 1, when?: number, gainScale = 1): boolean {
    const buffer = this.buffer;
    if (!buffer || this.volume <= 0) return false;
    const ctx = this.context;
    const now = when ?? ctx.currentTime;
    const rate = Math.max(0.125, Math.min(8, playbackRate));
    // --- review fix (uncap-all) --- a volume past 1 amplifies the clip (the master bus' limiter and soft clip guard the output)
    const level = this.volume * Math.max(0, gainScale);
    try {
      this.dropFinishedVoices(now); // --- fast-render ---
      while (this.voices.length >= MAX_VOICES) this.release(this.voices.shift()!, now);
      const duration = Math.min(buffer.duration / rate, MAX_VOICE_SEC);
      const fade = Math.min(VOICE_FADE_SEC, duration / 2);
      const source = ctx.createBufferSource();
      source.buffer = buffer;
      source.playbackRate.value = rate;
      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0, now);
      gain.gain.linearRampToValueAtTime(level, now + fade);
      gain.gain.setValueAtTime(level, now + duration - fade);
      gain.gain.linearRampToValueAtTime(0, now + duration);
      source.connect(gain);
      gain.connect(this.destination);
      const voice: Voice = { source, gain, start: now, level, fade, end: now + duration };
      source.onended = () => {
        const i = this.voices.indexOf(voice);
        if (i >= 0) this.voices.splice(i, 1);
        try {
          source.disconnect();
          gain.disconnect();
        } catch {
          /* already disconnected */
        }
      };
      source.start(now);
      source.stop(now + duration);
      this.voices.push(voice);
      return true;
    } catch (err) {
      console.error("Error playing hit sample:", err);
      return false;
    }
  }

  // --- fast-render ---
  /**
   * Forgets the voices that have played out by `now`, so only voices that really overlap are stolen – also when their
   * `ended` event has not fired yet (a fast export schedules the whole clip into an OfflineAudioContext before any of it plays).
   */
  private dropFinishedVoices(now: number) {
    let kept = 0;
    for (const voice of this.voices) if (voice.end > now) this.voices[kept++] = voice;
    this.voices.length = kept;
  }
  // --- end fast-render ---

  /** Fades a voice out quickly instead of cutting it (voice stealing), from the level its envelope has reached. */
  private release(voice: Voice, now: number) {
    try {
      const g = voice.gain.gain;
      g.cancelScheduledValues(now);
      g.setValueAtTime(voiceEnvelopeAt(voice, now), now); // --- review fix (audio) --- not g.value (see voiceEnvelopeAt)
      g.linearRampToValueAtTime(0, now + VOICE_FADE_SEC);
      voice.source.stop(now + VOICE_FADE_SEC);
    } catch {
      /* source already stopped */
    }
  }

  /** Stops every voice; the decoded clips stay cached. */
  dispose() {
    const now = this.context.currentTime;
    for (const voice of this.voices) this.release(voice, now);
    this.voices = [];
  }
}
