import { assetPath } from "@/lib/site";

/**
 * Built-in melody library. Each entry points to a MIDI file in /public/notes.
 * The files shipped with this repo are public-domain melodies generated by
 * scripts/generate-midi.py; drop any .mid file into public/notes and add it here
 * to extend the list.
 */
export interface Song {
  id: string;
  name: string;
  file: string;
}

export const SONGS: Song[] = [
  { id: "fur-elise", name: "Für Elise", file: assetPath("/notes/fur-elise.mid") },
  { id: "ode-to-joy", name: "Ode to Joy", file: assetPath("/notes/ode-to-joy.mid") },
  { id: "twinkle-twinkle", name: "Twinkle Twinkle Little Star", file: assetPath("/notes/twinkle-twinkle.mid") },
  { id: "happy-birthday", name: "Happy Birthday", file: assetPath("/notes/happy-birthday.mid") },
  { id: "canon-in-d", name: "Canon in D", file: assetPath("/notes/canon-in-d.mid") },
  { id: "jingle-bells", name: "Jingle Bells", file: assetPath("/notes/jingle-bells.mid") },
  { id: "greensleeves", name: "Greensleeves", file: assetPath("/notes/greensleeves.mid") },
  { id: "turkish-march", name: "Turkish March", file: assetPath("/notes/turkish-march.mid") },
  { id: "mountain-king", name: "In the Hall of the Mountain King", file: assetPath("/notes/mountain-king.mid") },
  { id: "william-tell", name: "William Tell Overture", file: assetPath("/notes/william-tell.mid") },
  { id: "entertainer", name: "The Entertainer", file: assetPath("/notes/entertainer.mid") },
  { id: "moonlight-sonata", name: "Moonlight Sonata", file: assetPath("/notes/moonlight-sonata.mid") },
];

/** Built-in wall-break sound effects (audio files in /public/wallBreak). */
export const WALL_BREAK_SOUNDS: { id: string; name: string; url: string }[] = [
  { id: "pop", name: "Pop", url: assetPath("/wallBreak/pop.wav") },
  { id: "chime", name: "Chime", url: assetPath("/wallBreak/chime.wav") },
];
