/**
 * Built-in melody library. Each entry points to a MIDI file in /public/notes.
 * The files shipped with this repo are public-domain melodies generated by
 * scripts/generate-midi.py; drop any .mid file into public/notes and add it here
 * to extend the list.
 */
export interface Song {
  id: string;
  name: string;
  file: string;
}

export const SONGS: Song[] = [
  { id: "fur-elise", name: "Für Elise", file: "/notes/fur-elise.mid" },
  { id: "ode-to-joy", name: "Ode to Joy", file: "/notes/ode-to-joy.mid" },
  { id: "twinkle-twinkle", name: "Twinkle Twinkle Little Star", file: "/notes/twinkle-twinkle.mid" },
  { id: "happy-birthday", name: "Happy Birthday", file: "/notes/happy-birthday.mid" },
  { id: "canon-in-d", name: "Canon in D", file: "/notes/canon-in-d.mid" },
  { id: "jingle-bells", name: "Jingle Bells", file: "/notes/jingle-bells.mid" },
  { id: "greensleeves", name: "Greensleeves", file: "/notes/greensleeves.mid" },
  { id: "turkish-march", name: "Turkish March", file: "/notes/turkish-march.mid" },
  { id: "mountain-king", name: "In the Hall of the Mountain King", file: "/notes/mountain-king.mid" },
  { id: "william-tell", name: "William Tell Overture", file: "/notes/william-tell.mid" },
  { id: "entertainer", name: "The Entertainer", file: "/notes/entertainer.mid" },
  { id: "moonlight-sonata", name: "Moonlight Sonata", file: "/notes/moonlight-sonata.mid" },
];

/** Built-in wall-break sound effects (audio files in /public/wallBreak). */
export const WALL_BREAK_SOUNDS: { id: string; name: string; url: string }[] = [
  { id: "pop", name: "Pop", url: "/wallBreak/pop.wav" },
  { id: "chime", name: "Chime", url: "/wallBreak/chime.wav" },
];
