import { assetPath } from "@/lib/site";

/**
 * Built-in melody library. Each entry points to a MIDI file in /public/notes.
 * The files shipped with this repo are public-domain melodies generated by
 * scripts/generate-midi.py; drop any .mid file into public/notes and add it here
 * to extend the list. Wrap the path in assetPath() so it resolves when the site is
 * served from a sub-folder (GitHub Pages project sites).
 */
export interface Song {
  id: string;
  name: string;
  file: string;
}

export const SONGS: Song[] = [
  { id: "fur-elise", name: "Für Elise", file: assetPath("/notes/fur-elise.mid") },
  { id: "ode-to-joy", name: "Ode to Joy", file: assetPath("/notes/ode-to-joy.mid") },
  { id: "twinkle-twinkle", name: "Twinkle Twinkle Little Star", file: assetPath("/notes/twinkle-twinkle.mid") },
  { id: "happy-birthday", name: "Happy Birthday", file: assetPath("/notes/happy-birthday.mid") },
  { id: "canon-in-d", name: "Canon in D", file: assetPath("/notes/canon-in-d.mid") },
  { id: "jingle-bells", name: "Jingle Bells", file: assetPath("/notes/jingle-bells.mid") },
  { id: "greensleeves", name: "Greensleeves", file: assetPath("/notes/greensleeves.mid") },
  { id: "turkish-march", name: "Turkish March", file: assetPath("/notes/turkish-march.mid") },
  { id: "mountain-king", name: "In the Hall of the Mountain King", file: assetPath("/notes/mountain-king.mid") },
  { id: "william-tell", name: "William Tell Overture", file: assetPath("/notes/william-tell.mid") },
  { id: "entertainer", name: "The Entertainer", file: assetPath("/notes/entertainer.mid") },
  { id: "moonlight-sonata", name: "Moonlight Sonata", file: assetPath("/notes/moonlight-sonata.mid") },
];

/** Built-in wall-break sound effects (audio files in /public/wallBreak). */
export const WALL_BREAK_SOUNDS: { id: string; name: string; url: string }[] = [
  { id: "pop", name: "Pop", url: assetPath("/wallBreak/pop.wav") },
  { id: "chime", name: "Chime", url: assetPath("/wallBreak/chime.wav") },
  // --- boris-glass --- a short glass shatter (scripts/generate-sounds.py): the default of Glass Smash
  { id: "glass", name: "Glass", url: assetPath("/wallBreak/glass.wav") },
];

// --- boris-glass ---
/** Id of the built-in wall-break clip a mode plays when no wall-break sound was chosen (Glass Smash shatters its panes with the glass clip). */
export const MODE_WALL_BREAK_SOUNDS: Partial<Record<string, string>> = { glass: "glass" };

/** The wall-break sound in effect: the chosen one, else the mode's own default (null = the classic arpeggio). */
export function modeWallBreakSound(mode: string, chosen: string | null): string | null {
  if (chosen) return chosen;
  const id = MODE_WALL_BREAK_SOUNDS[mode];
  return id ? (WALL_BREAK_SOUNDS.find((snd) => snd.id === id)?.url ?? null) : null;
}
// --- end boris-glass ---

/**
 * Presets and share links may carry a wall-break sound URL saved under another base path
 * (or a dead blob: URL from a custom upload). Maps built-in sounds back to their current URL,
 * drops dead uploads and leaves anything else untouched.
 */
export function normalizeWallBreakSound(value: string | null | undefined): string | null {
  if (!value) return null;
  if (value.startsWith("blob:")) return null;
  const builtIn = WALL_BREAK_SOUNDS.find((snd) => value === snd.url || value.endsWith(`/wallBreak/${snd.id}.wav`));
  return builtIn ? builtIn.url : value;
}
